### ISSUE TITLE
dependency on custom_derive in "release" build?

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#10]
Hm, I wonder about the dependency on custom_derive.

The thing is, [src/derive_builder.rs](https://github.com/colin-kiegel/rust-derive-builder/blob/master/src/derive_builder.rs) does not really depend on it. Only our tests+examples and the consumer need the custom_derive crate.

Can we reflect this fact in Cargo.toml? Otherwise our consumers might end up building duplicates of the custom_derive crate. Alternatively we could perhaps re-export custom_derive, but this seems to contradict the general idea of using custom_derive with multiple extensions.

@killercup: Well, not really a big issue, but what do you think?

**Comment by killercup** [comment]
Oh, right. That should've been a dev-dependency. (Please mention the
version s of custom_derive we support if you change that.)

There is no way to reexport macros on stable IIRC.


Colin Kiegel <notifications@github.com> schrieb am So. 7. Aug. 2016 um
11:09:

**Comment by colin-kiegel** [comment]
done.

I'd say `v0.1.0` will only be guaranteed to work with `v0.1.5` because this is exactly what we have tested. For stronger guarantees we might want to figure out a way to extend testing to different versions of `custom_derive`.
