### ISSUE TITLE
Release v0.5.0 with updated defaults

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#102]
The `private_fields` and `struct_default` features have been sitting behind feature flags for some time now. Making those default will give more users a correct-by-default experience and will let us remove old code paths sooner.

**Comment by colin-kiegel** [comment]
Yes, that sounds good to me. It's time for a new release. ;-)

I will return from my holidays tomorrow morning.

**Comment by colin-kiegel** [comment]
I'm working on it now :-)

**Comment by colin-kiegel** [comment]
:tada: done :-)
