### ISSUE TITLE
The use of default="..." still requires implementation of Default

### ISSUE THREAD

**Issue by pronebird** [colin-kiegel/rust-derive-builder#103]
Hi,

I defined a struct with default values but I am not able to compile it, maybe you could give me a pointer. (I use v0.5)

```
enum Toy { Soldier, }
#[derive(Builder, Default)]
#[builder(setter(into))]
struct Toybox {
  #[builder(default="Toy::Soldier")]
  toy: Toy,
}
```

`cargo build` throws:

```
the trait `std::default::Default` is not implemented for `ToyShop::Toy`
```

Why do I have to implement `Default` if I explicitly provide `default` value?

**Comment by crepererum** [comment]
Because you try to derive Debug for the whole struct in line 2? Does the error disappear when you remove that?

**Comment by colin-kiegel** [comment]
Yes, `#[builder(default="Toy::Soldier")]` has no effect on `#[derive(Default)]`.
