### ISSUE TITLE
How to put custom attributes on generated Builder?

### ISSUE THREAD

**Issue by Boscop** [colin-kiegel/rust-derive-builder#105]
I want to use this crate to derive a builder for my ORM Update structs with diesel.
Handwritten they look like:
```rust
#[derive(Clone, Debug)]
#[derive(AsChangeset)]
#[table_name = "tablets"]
pub struct UpdateTablet {
	updated_at: NaiveDateTime,
	customer_id: Option<Option<i64>>,
	logged_in: Option<i64>,
	latitude: Option<f64>,
	longitude: Option<f64>,
}
```
But I want to have a builder for that with the attributes:
```rust
#[derive(Clone, Debug)]
#[derive(AsChangeset)]
#[table_name = $table_name]
```

How can I put those attributes on the generated builder?

**Comment by TedDriggs** [comment]
At the moment, that's not supported. @colin-kiegel and I have gone back and forth a couple times on whether we want that; there are arguments for the flexibility, but it could easily end up in really ugly meta-programming messes.

**Comment by colin-kiegel** [comment]
See #90.
