### ISSUE TITLE
Crate Maintenance

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#106]
It's been a while since I worked on this crate. And I have to admit that right now I'm focusing on other things. At the end of the day, there's not enough time for me to maintain and improve this crate right now.

If anyone is interested to pick up the crate maintenance and can prove to be trustworthy, I'd be ready to hand it over (including crates.io ownership).

cc @TedDriggs 

PS: It took me some time to reach this conclusion, but as they say: You can't have the cake _and_ eat it. ;-)

**Comment by TedDriggs** [comment]
Unfortunately, I'm in a similar position: My day job hasn't left me much time for OSS work, and as a result I haven't been able to contribute much.

**Comment by TedDriggs** [comment]
@colin-kiegel I've had a little time open up. I won't be able to do much feature work, but I should be able to test and release if that's helpful.

**Comment by colin-kiegel** [comment]
@TedDriggs great, some minor polish seems to be most wanted right now: #104.

PS: you can publish to crates.io if you push a new tag to the master branch. Travis will then do the publishing, see. Or contact me if that doesn't work. :-)

**Comment by fluffysquirrels** [comment]
I created issue <https://github.com/colin-kiegel/rust-derive-builder/issues/107> ("Fix the Travis build on master, rev ea8c575") to work on the immediate problems. I opened PR <https://github.com/colin-kiegel/rust-derive-builder/pull/108> that fixes the problems.

@colin-kiegel can you review, merge, and publish this or give me the permissions to do so? Thanks!

**Comment by colin-kiegel** [comment]
I pushed a new `v0.5.1` tag to github. `travis.toml` has a deploy-hook for new tags in the master branch, which should then publish a release to crates.io. This way, everyone with write access to this repository should be able to publish releases. If this fails, I will publish manually later. :-)

@fluffysquirrels if you contribute more and if @TedDriggs agrees, I can grant you write access, too. :-)

**Comment by fluffysquirrels** [comment]
@colin-kiegel sounds great. Thanks for the quick turnaround.

**Comment by colin-kiegel** [comment]
:tada: `v0.5.1` was published automagically by Travis: https://travis-ci.org/colin-kiegel/rust-derive-builder/jobs/317314086#L1236-L1256 :-)

**Comment by Dylan-DPC** [comment]
Hey Colin

Can help to co-maintain this if needed. Let me know. 😄

**Comment by colin-kiegel** [comment]
@Dylan-DPC, @fluffysquirrels, @TedDriggs thx for your willingness to support this crate. :heart: :+1:

Would you like to work as a team?
And in what way do you want to contribute ...
- answering user questions
- discussion of feature requests
- implementation of features / writing PRs
- code review
- (packing releases - this is actually semi-automated right now)
- fixing bugs
- writing docs
- polishing
- ...(you name it)?

@TedDriggs I already trust you with general design decisions. Would you like to 'lead' this crates development in perhaps having the final say over design decisions? This job would mainly come with code review and discussion of feature requests.

**Comment by TedDriggs** [comment]
@colin-kiegel I can do that. I'll flag you on any discussions where I think you might have an opinion / you and I might see things differently.

**Comment by colin-kiegel** [comment]
@TedDriggs Cool, thx. :-) I want to give you a lot of leeway in return. I feel open to just doing it _your_ way, even if we have slightly different opinions from now on.. Of course you can consult me just like anyone else, when you are not sure about a design decision.

@Dylan-DPC @fluffysquirrels If you still want to help, please direct your contributions and questions to @TedDriggs. As far as I know, his time is limited, so I guess your help will be very welcome. ;-)

**Comment by Dylan-DPC** [comment]
hey @colin-kiegel 

so yeah I am fine with working as a team with Ted & Alex. I am open to contributing in different areas wherever there is a need. Right now I don't know much about this crate so it might take a while to submit PRs and take part in a lot of feature discussions. But i contribute in other aspects such as managing releases, reviewing PRs maybe even fixing bugs. 

Thanks

**Comment by fluffysquirrels** [comment]
Hi all,

Really happy to see some commitment to this crate.

I'd contribute reviews, ideas, bug fixes, documentation, small features. Big features I'm less likely to find the time for, unless I need them myself. Feel free to @ me on any relevant issues or email me (address on my github profile).

**Comment by Dylan-DPC** [comment]
hey @colin-kiegel 

Any update on this?

**Comment by azriel91** [comment]
Hiya @colin-kiegel, friendly ping to find maintainers :slightly_smiling_face:
(roundabout way of saying I have a PR that needs a review, whether by yourself / someone else)

**Comment by fluffysquirrels** [comment]
@azriel91 Thanks for contributing to the crate! I can take a look at this

**Comment by azriel91** [comment]
Hiya!
In a bid to revive this (and save myself some tech tebt), @TedDriggs are you still keen to lead development / maintenance on this crate?
Otherwise, how about asking in the Rust users forum?

**Comment by Dylan-DPC** [comment]
@azriel91 its okay mate. the 3 of us or even without Ted it is fine.. we just need to get started

**Comment by Dylan-DPC** [comment]
@colin-kiegel can you create a gitter channel for easier communication between the co-maintainers?

**Comment by colin-kiegel** [comment]
I never worked with gitter before, @Dylan-DPC.

What do the other Co-Maintainers think about using gitter?
cc @azriel91 @fluffysquirrels @TedDriggs

**Comment by azriel91** [comment]
I've been using gitter to chat with the Amethyst devs &mdash; it's got markdown messages (yay!) and good integration with github.
I haven't been using Discord but that's another good one if someone prefers that.

**Comment by jplatte** [comment]
o/

I'd like to offer helping to maintain this crate as well, since I'm going to be needing it [for ruma/ruma-events](https://github.com/ruma/ruma-events/issues/100). To get things moving a bit, I just created a chat room [on matrix](https://matrix.to/#/#rust-derive-builder:matrix.org) since the Gitter room apparently never ended up being created. Feel free to ignore it and finally set up the Gitter room if you prefer – I can still join via Matrix because it bridges to almost everything else :)

**Comment by TedDriggs** [comment]
The crate's been pretty stable for a while now; I'm happy to look at issues and review PRs, but I'm not sure how much active maintenance it needs at the moment, and given that this predates a lot of edition changes with 2018, I've been inclined to be conservative in changing the crate for fear of breaking existing users.

**Comment by jplatte** [comment]
Hmmm.. Sounds almost like I should be creating my own crate for my needs. Will investigate the current code base in the coming days.

**Comment by TedDriggs** [comment]
With the 0.10.0 release, the crate is still very open to accepting and reviewing PRs, but I don't think we need a "help-wanted" issue calling for maintainers.

**Comment by Dylan-DPC** [comment]
Sorry that i haven't looked at this crate much since volunteering to do so, but something I guess i'll try and push to do more in the future
