### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by voider1** [colin-kiegel/rust-derive-builder#109]
I have a lot of structs which have fields which NEED to be filled, validation functions are a bit overkill for this. Is there another easier way in which I could achieve this?

**Comment by TedDriggs** [comment]
If the field isn't optional and you don't specify `#[builder(default)]` then calling `build` without setting that field will already produce an error.

**Comment by colin-kiegel** [comment]
@TedDriggs thx :-)
@voider1 does this answer your question?

**Comment by shimunn** [comment]
Is there a reason why my fields still have to implement Default even though I'm not using #[builder(default)]?

**Comment by TedDriggs** [comment]
@shimunn can you provide an example please?

**Comment by shimunn** [comment]
```
#[macro_use]
extern crate derive_builder;

use std::io;

pub struct Peer;

#[derive(Debug, Builder, PartialEq, Eq)]
#[builder(pattern = "owned")]
pub struct Interface<I>
where
    I: Iterator<Item = io::Result<Peer>>,
{
    pub id: u64,
    pub peers: I,
}

fn main() {
    let builder: InterfaceBuilder<Box<Iterator<Item = io::Result<Peer>>>> = InterfaceBuilder::default();
    println!("Hello, world!");
}
```

Which fails with:

```
the trait `std::default::Default` is not implemented for `dyn std::iter::Iterator<Item = std::result::Result<Peer, std::io::E
rror>>`
```

Which shouln't be a problem since a builder is just a struct of Option<T> where the default for a type that doesn't implement Default should be None. At least that's my understanding, or is there another constructor to call instead of `InterfaceBuilder::default();` to obtain an instance of the builder ?
