### ISSUE TITLE
first release?

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#11]
@killercup: ready to tag "v0.1.0" and publish, if you are. :-)

**Comment by killercup** [comment]
Before you publish this:

- Do you have some edge cases you want to add tests for?
- Also, do you want to expand the readme with an example (if you haven't
already)?
- last but not least, dong forget to add ALL the meta tags to `Cargo.toml`
before you `cargo publish` 😄

Then we are good to go!


Colin Kiegel <notifications@github.com> schrieb am So. 7. Aug. 2016 um
11:24:

**Comment by colin-kiegel** [comment]
1) Meta tags should be complete: I already added description, repository, documentation, license and
```
keywords = ["custom", "derive", "macro", "builder", "setter", "struct"]
readme = "Readme.md"
```
So even the readme should be _indexed_ by crates.io, too.

2.) Readme is updated with a simplified example. Do we want to keep the disclaimer until v1.0 or are we confident? Right now, I just kept it: _This is a work in progress. Use it at your own risk._

3) We can add a testcase / example for chaining a 'consuming' terminating method? But IMO this would not block a release right now.

You can still comment - I will not publish before the late evening.

**Comment by killercup** [comment]
Thanks!

1) I'd add "custom derive" as a keyword; don't know if people will search
for "custom", "struct", or "setter". IIRC you can set at most 6 keywords.

2) I'll have a look at the readme but assume it's fine :)

3) I wouldn't block on this either. It's 0.1, not 1.0 ;)


Colin Kiegel <notifications@github.com> schrieb am So. 7. Aug. 2016 um
13:35:

**Comment by colin-kiegel** [comment]
done. :tada: :package:

https://crates.io/crates/derive_builder 

But only 5 keywords are allowed and no whitespaces. I removed "custom", because it should always come in a pair with another keyword.
