### ISSUE TITLE
Emit field - but not setter - to support setter defined in user code

### ISSUE THREAD

**Issue by lobisquit** [colin-kiegel/rust-derive-builder#110]
I would like to use, in my code, the useful `#[builder(setter(skip))]` option to write a custom setter for a struct field.

Expanding macros I noticed though that such field is marked in the builder as `std::marker::PhantomData<...>`, and I don't know how to deal with it.
Other generated setters assign actual value to common `Option<...>`: how can the same be done with `PhantomData<...>`?

**Comment by fluffysquirrels** [comment]
A PhantomData instance cannot be written to, it's just there for the
compiler to track types. Can you try writing the value somewhere else in
the builder struct? If not maybe we need to support skipping setter but
leaving a field to write. Can your use case be supported by validatiob in a
custom build method?

**Comment by Dylan-DPC** [comment]
@lobisquit any updates on this?

**Comment by lobisquit** [comment]
Hi, sorry but I currently have no time to work on the project that rised this issue, I think I will try to work it out in the future, but sadly not soon.

**Comment by TedDriggs** [comment]
@lobisquit the best way to address this is probably to add something that says "I'm going to write my own setter". At that point, we could emit the field but not the setter.

**Comment by mwilliammyers** [comment]
My use case for this is to add an item to a `Vec` before setting it. This cannot be accomplished as a `Default` because I want to add the item to the `Vec` regardless if the field was specified or not in the builder. This could be done with a custom builder, but would be much more ergonomic as a custom setter fn, because all the other fields can be handled normally.

**Comment by Luro02** [comment]
In my use case I want to hide a field type from the user

```rust
#[derive(Builder)]
struct Example {
    #[builder(setter(skip))]
    data: BTreeMap<usize, OtherStruct>,
    // other fields omitted
}

impl ExampleBuilder {
    pub fn data(&mut self, values: Vec<OtherStruct>) -> &mut Self {
        let mut result = BTreeMap::new();

        for value in values {
            result.insert(value.number, value);
        }

        self.data = Some(result);
        self
    }
}
```

**Comment by TedDriggs** [comment]
@Luro02 could you handle your use-case by doing the following?

1. Make the setter private
2. Change the setter name to `inner_your_field`
3. Expose the public setter manually

**Comment by TedDriggs** [comment]
It looks like `setter(custom)` should handle this.
