### ISSUE TITLE
Static builder validation via generic type parameters

### ISSUE THREAD

**Issue by bowbahdoe** [colin-kiegel/rust-derive-builder#113]
When we generate a builder as the package is, when we finally call .build() we are given a Result because its possible for a dev to leave fields blank by mistake, which would cause an error.

Hypothetically, we could avoid this by making a whole lot of intermediate structs representing every possible combination of fields to be filled in, but statically making those for every possible combination would be an N^2 task which would bleed over into compile time and executable size.

Is there a way to generate intermediate structs, but only for the build orders that are used? For example, if we have this struct 

```rust
#[derive(Default, Debug, Builder)]
struct Apple {
    color: String,
    taste: String,
    size: String
}
```

If we were to make an intermediate builder for each possible order of filling in the struct we would get out these structures.

```rust
struct AppleBuilder {
    color: Option<String>,
    taste: Option<String>,
    size: Option<String>
}

struct AppleIntermediate1 {
    color: Option<String>,
    taste: Option<String>,
    size: String
}

struct AppleIntermediate2 {
    color: Option<String>,
    taste: String,
    size: Option<String>
}

struct AppleIntermediate3 {
    color: String,
    taste: Option<String>,
    size: Option<String>
}

struct AppleIntermediate4 {
    color: String,
    taste: String,
    size: Option<String>
}

struct AppleIntermediate5 {
    color: Option<String>,
    taste: String,
    size: String
}
```

(This would obviously be much more for a structure of the size that would justify a builder)

But if all the usages in the code go like

```rust
let apple = AppleBuilder::default().color(...).taste(...).size(...).build()
```

Theoretically, we would only need to generate intermediates 3 and 4.

(TL;DR is there a way to use this and also eliminate the possibility of runtime errors?)

**Comment by fluffysquirrels** [comment]
Perhaps with one intermediate struct with a generic type parameter per
field, with the type parameter statically representing if the field is
present or missing.

Unfortunately this won't compile if a field is set only on some code paths.
No possible static analysis could validate this case (this would be
equivalent to the halting problem). This use case is common (in my
experience).

Another alternative I have played with writing by hand is to have a
constructor for the builder struct that takes a "required fields" struct as
a parameter. The consumer constructs the required fields struct with an
object literal. Any optional fields on the builder can be set fluently. You
could probably use that pattern with this crate by having a field with
private setter.

In my usage I have been happy enough with runtime validation, which in
practice has caught errors early in development.

**Comment by TedDriggs** [comment]
+1 to @fluffysquirrels' comments. I don't think this is something the crate would accept without a lot of review and discussion (possibly even a light RFC?) first.

**Comment by colin-kiegel** [comment]
This discussion just reminds me of this paper about `Session Types for Rust`. It discusses using generic type parameters to validate state transitions in a communication protocol:
http://munksgaard.me/papers/laumann-munksgaard-larsen.pdf

It's definetely an interesting idea and it was already on my _someday_ list. ^^
As @fluffysquirrels points out, it won't support dynamic code paths, unless the generic type gets _boxed_ again (=converted into a trait object). It might be a nice addition for this crate.

**Comment by bowbahdoe** [comment]
https://immutables.github.io/immutable.html#staged-builder

Immutables in java uses this as a way to ensure compile time safety. Is this relevant?

**Comment by TedDriggs** [comment]
This is different enough from the current crate that I think it should be a new library rather than working off of this one.
