### ISSUE TITLE
Special setter behavior for `Vec` fields?

### ISSUE THREAD

**Issue by pwoolcoc** [colin-kiegel/rust-derive-builder#114]
Would it be possible to have special setter methods for `Vec` fields? That is, instead of just a field for setting the whole vec at once, the user could opt-in to also generating setters that `.push` an element of type `T` onto a field with type `Vec<T>`?

The generated code could look something like

```
struct FooBuilder {
    bars: Option<Vec<Bar>>
}

impl FooBuilder {
    ...
    pub fn bars<VALUE: Into<Vec<Bar>>>(&mut self, value: VALUE) -> &mut Self {
        self.bars = Some(value.into());
        self
    }
    pub fn bar<VALUE: Into<Bar>>(&mut self, value: VALUE) -> &mut Self {
        if let Some(ref mut bars) = self.bars {
            bars.push(value.into());
        } else {
            self.bars = Some(vec![value.into()]);
        }
        self
    }
    ...
}
```

Ideally I'd like to have this for any `.push`-able type, but until we have collections traits I think having it just for `Vec` could be helpful.

**Comment by TedDriggs** [comment]
Conceptually it's doable. I don't think it'd be possible for the names to be automatically generated to be singular or plural, but other than that it doesn't seem too terrible. What are the cases you have in mind for this feature?

**Comment by TedDriggs** [comment]
FWIW, I have some experience implementing this in [`darling`](https://github.com/TedDriggs/darling/blob/master/core/src/codegen/field.rs#L86). It wasn't too bad, but I was disappointed to find that there isn't a good trait to latch onto which would allow arbitrary types to be used.

**Comment by carloscasalar** [comment]
It could by like [@Singular annotation in lombok](https://projectlombok.org/features/Builder) specifying   the singular method name. I Think it could be something like this:

```rust
#[derive(Default, Builder, Debug)]
struct FooBuilder {
    #[builder(singular(name = "bar"))]
    bars: Option<Vec<Bar>>
}
```

**Comment by cheako** [comment]
Don't leave out hashmap, probably implement something for all the std collections.

**Comment by cheako** [comment]
I'm writing a game engine like TheCherno's Hazel.  He has this habit of creating a class, calling a setter on it and then passing the results to another class's setter.

https://github.com/TheCherno/Hazel/blob/30b5c242986c67ab20709980f88ca115e65e1261/Sandbox/src/SandboxApp.cpp#L25

30,31,36

I would like to take the builder a tad further and add a material system.  Currently 209,214 draw the same square, but with different shader programs.

I want to add shader programs to the VertexArray "by name/String".  I could just have a default HashMap and do my inserting after build(), but that just doesn't seem right.

For reference, I haven't uploaded my changes so this link will change: https://gitlab.com/cheako/hazel-rs/blob/master/src/renderer.rs#L66

**Comment by TedDriggs** [comment]
@cheako unfortunately, there doesn't seem to be a standard way to add an item to an arbitrary collection type, or even a trait for that.

**Comment by cheako** [comment]
@TedDriggs This issue was about Vec<_> and I think I was saying HashMap<_, _> also plz.  Nothing to do with generalization across multiple collection types.

Thanks.

**Comment by TedDriggs** [comment]
That’s the problem - a proc macro can’t access type information, so I’d need separate macro attributes for Vec vs HashSet. That’s a level of programming-via-attribute I’m not sure the crate should support, especially when it’s possible to add completely arbitrary functions with your own impl block on the builder type.

**Comment by cheako** [comment]
If a member can't be identified as Vec/HashSet one way, then do so by another.  Don't know what all doesn't work, but have you tried by name prefix/suffix?

**Comment by cheako** [comment]
As for other ways to do this, I'm sure there are hundreds!  Documentation is usually the way ppl find out what to do.

**Comment by helgoboss** [comment]
I think just supporting `Vec` for now would be a big win already.
