### ISSUE TITLE
Discussion: Move derive-builder to use darling

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#115]
A while back I started working on a new library called [`darling`](https://github.com/TedDriggs/darling) which was aimed at making options parsing serde-level easy for proc-macro crates. Specifically, darling tries to remove most of the code in [src/options/mod.rs](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/src/options/mod.rs) in this project, replacing it with codegen.

The advantage of doing this would be less code that's specific to derive-builder. There was some discussion on #95 about this in which @colin-kiegel expressed concerns about the dependencies another similar library brought in, but I don't see that being as big an issue: The dependent libraries aren't used in shipping code.

**Comment by colin-kiegel** [comment]
I think my basic concern was the additional dependency on `error_chain` through `darling`. But I like the general refactoring idea, so please go ahaed if you like to. :+1:

**Comment by TedDriggs** [comment]
@colin-kiegel `error-chain` isn't depended on by `darling`, so it shouldn't wind up in consuming projects... I don't think?

**Comment by colin-kiegel** [comment]
@TedDriggs Oh, I see. :sweat_smile: What about [this ticket](https://github.com/TedDriggs/darling/issues/21) then?

**Comment by TedDriggs** [comment]
I'm still investigating `failure` - haven't had a ton of time, and I've seen some people express concerns about the library.

**Comment by Dylan-DPC** [comment]
@TedDriggs what concerns exactly? we can put them across in the ecosystem-wg
