### ISSUE TITLE
Feature: Allow "strip option" on setters

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#116]
Consider a case where I have the following:

```rust
// The `from_variants` crate will generate From<String> for Foo and From<u32> for Foo impls
#[derive(FromVariants)]
pub enum Foo {
    Bar(String),
    Baz(u32),
}

#[derive(Builder)]
#[builder(setter(into))]
pub struct Built {
    value: Option<Foo>,
    other: Option<Foo>,
}
```

I'd like the user of this to write:

```rust
fn make_built() -> Built {
    BuiltBuilder::default()
        .value(17)
        .build()
        .unwrap()
}
```

In this case, `value` should be initialized to `Some(Foo::Baz(17))` and `other` should remain `None`.

What I'm imagining is there's some new setter option, called `always_some` or `pierce_option` or `strip_option`. It would work at the struct and field level, though using it on a field which wasn't an option would produce an error. When it's present, if the type is exactly "Option" then we grab the inner type and use that for the setter, wrapping the provided value in a `Some` in the setter.

# Problems
1. We have to break open the type to figure out the non-optional part, which isn't always going to work.

**Comment by davidB** [comment]
Any suggestion about how to start to try to implement this feature ? (I never made a derive, but I'll provide a PR if I have something usefull).

Context, I would like to provide an easy way to create struct generated automaticaly from a json-schema (so lot Option, and enum,...).

**Comment by TedDriggs** [comment]
Thanks for offering to look into it. For this feature, you're going to need two parts:

1. An update to the `Field` struct in `darling_opt.rs` [here](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/src/options/darling_opts.rs#L177) where you allow the user to pass the optional `strip_option` flag.
2. An update to the generated code which attempts to look inside the type of the field and get the underlying value if it's an `Option<T>`, or emit a compile error otherwise.

**Comment by davidB** [comment]
@TedDriggs 
I guess this ticket could be closed.
When do you plan to "cargo publish 0.7.2" (I need it to publish my own crate ;-) ) ?

**Comment by TedDriggs** [comment]
Sorry, running the job to publish now.
