### ISSUE TITLE
Feature: Implement Default for struct based on Builder defaults

### ISSUE THREAD

**Issue by davechallis** [colin-kiegel/rust-derive-builder#117]
It would be convenient to have the option of creating a Default implementation for a struct using the same defaults as specified in the builder.

E.g. current behaviour is:

```
#[macro_use]
extern crate derive_builder;

#[derive(Builder, Default)]
pub struct Foo {
    #[builder(default = "0.3")]
    val: f32,
}

fn main() {
    let foo = Foo::default();
    println!("{}", foo.val);

    let foo = FooBuilder::default().build().unwrap();
    println!("{}", foo.val);
}
```
In this case, the default value of `Foo::default().val` is `0` vs. `0.3` from the builder default.

Would be useful to be able to do something like
```
#[derive(Builder, DefaultFromBuilder)]
pub struct Foo {
    #[builder(default = "0.3")]
    val: f32,
}
```
which would then generate:
```
impl Default for Foo {
    fn default() -> Self {
        Foo { val: 0.3 }
    }
}
```

**Comment by TedDriggs** [comment]
This seems like it _should_ work. Are you imagining that we'd insert `Default::default()` for any field that didn't have a default specified via `builder` attribute?

**Comment by davechallis** [comment]
@TedDriggs yup, exactly, so it would end up with the same behaviour as `#[derive(Default)]` if the builder didn't contain any default from the builder.

**Comment by TedDriggs** [comment]
What's the reason for generating this using `derive_builder` instead of implementing it explicitly and having `derive_builder` pick up on that impl?

Conceptually, I'm on the fence about this right now because my general design principle is "follow Serde's example", and Serde doesn't provide affordances for implementing the `Default` trait even though it has the same defaulting behaviors. @colin-kiegel has previously raised the good point that we don't want to move too much data definition into the attribute meta-language.

**Comment by davechallis** [comment]
@TedDriggs that would work for my use case too, I wasn't sure how to achieve it though.

I.e. I thought that `derive_builder` automatically created an `impl Default for FooBuilder` based on `#[builder(default)]` attributes, so it wasn't clear to me how to pick up values from e.g. `impl Default for Foo` (other than using something like `[builder(default = "Foo::default().val")]` or similar.

I'm migrating some configuration code that's got ~40 fields with default values, so mostly trying to minimise boilerplate and duplication where possible.

**Comment by TedDriggs** [comment]
`#[builder(default)]` causes us to create an instance of the target type using `Default::default()` and use that to get values for fields where the setter wasn't invoked. So you should write an `impl Default` and then set `#[builder(default)]` at the struct level to have us use those values.

**Comment by davechallis** [comment]
Ah, perfect, that does exactly what I'd need. I didn't realise `#[builder(default)]` could be set at the struct level, I'd set it to `#[builder(default)]` on each field individually, which then used the default value for that type (e.g. 0.0 for f32), rather than from the struct's default.
