### ISSUE TITLE
Update crates.io credentials on Travis

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#133]
Publish-by-tag is broken due to a 403 in `cargo publish` ([travis log](https://travis-ci.org/colin-kiegel/rust-derive-builder/jobs/386707259#L1187)). This is currently blocking the publication of v0.5.3 and of v0.6.0

**Comment by colin-kiegel** [comment]
@TedDriggs In crates.io I sent you invitations as Co-Owner of `deriver_builder` and `derive_builder_core`

**Comment by timvisee** [comment]
It would be awesome it this could be resolved as soon as possible.

`v0.6.0` has some important fixes I depend on. I'm currently unable to release my crate due to `v0.6` not being publicly available on crates.io yet.

**Comment by TedDriggs** [comment]
@timvisee, Colin has given me ownership of the crate now, so I'm ready to publish v0.6 as soon as I figure out what's changed to cause the nightly test to fail. I think it's something in Rust, rather than the crate.

**Comment by timvisee** [comment]
@TedDriggs Thanks a lot, that's great!

I'll try to take a look into what is causing this problem as well. Maybe I can be of any help.

And yes, it must be something related to Rust as the very same commit only started failing 2 months ago.

**Comment by TedDriggs** [comment]
@timvisee for now, I've moved the `no_std` test to be an allowed failure, so I think I'll be able to publish momentarily.

**Comment by TedDriggs** [comment]
Okay, 0.6.0 is live
