### ISSUE TITLE
Why the setters return a mutable reference to self?

### ISSUE THREAD

**Issue by amreo** [colin-kiegel/rust-derive-builder#135]
You have written in the README.md that the setters return a &mut Self. Why do you choose to return a &mut Self instead of Self?
```
    pub fn special_info<VALUE: Into<i32>>(&mut self, value: VALUE) -> &mut Self {
        let mut new = self;
        new.special_info = Some(value.into());
        new
    }
```

**Comment by TedDriggs** [comment]
We support the consuming pattern, but it makes it hard to write a builder that does everything, including the `build` step, in a fluent interface fashion.
