### ISSUE TITLE
Howto: Skip `Default` altogether.

### ISSUE THREAD

**Issue by dpc** [colin-kiegel/rust-derive-builder#136]
I'd like the builder to be instantiated by a custom method (that requires some initial arguments), and I'd like it to be impossible to start with `FooBuilder::default()`.

Is this currently possible?

**Comment by TedDriggs** [comment]
Good question; I don't think so. You can create a method of your own by adding an `impl FooBuilder` block, but I don't think we allow skipping the default.

Why do you need to skip it? All the fields are currently `Option`, so we know how to deal with the case where someone starts with nothing.

**Comment by dpc** [comment]
@TedDriggs The only reason was to enforce that a value is provided at compile time, as opposed to the current method, where it panics at runtime.

**Comment by glennpratt** [comment]
Rather than making it impossible, perhaps you just want default to be private.

**Comment by TedDriggs** [comment]
A trait impl can't be private, so we'd have to skip the creation. @dpc would you expect `derive_builder` to generate those required fields as non-options in the `Builder` type, or could they still be options that you knew would never be `None`?

**Comment by dpc** [comment]
Non-options, I guess, but it's been a while since I reported the issue and moved on with my life. :D

**Comment by TedDriggs** [comment]
I'm thinking that you'd have to manually implement that function, but we might be able to do something like this:

```rust
#[derive(Builder)]
#[builder(skip_new)]
pub struct MyStruct {
    #[builder(upfront)]
    my_field: String,
    my_second_field: String,
}
```

That would generate:

```rust
pub struct MyStructBuilder {
    my_field: String,
    my_second_field: Option<String>,
}

impl MyStructBuilder {
    pub fn my_second_field(&mut self, value: String) -> &mut Self {
        self.my_second_field = Some(value);
        self
    }

    pub fn build(self) -> MyStruct {
        // omitted
    }
}
```

It'd be up to you to write the constructor function.

**Comment by dpc** [comment]
@TedDriggs This looks good, yes. No time pressure from my side. I usually just report improvement ideas and move on with whatever works.

**Comment by mmstick** [comment]
I have a large number of types which the builder should not be able to define. Essentially, a type which must be instantiated with `T::new(&required1, &required2, required3)`, but all other fields should be build-able. Having a `#[builder(skip)]` option, as serde does, would be nice.

**Comment by TedDriggs** [comment]
@mmstick the crate has that with `#[builder(setter(skip))]`, but it will fall back to defaults rather than requiring the fields be declared upfront.

**Comment by mmstick** [comment]
It doesn't work though because the entire struct must derive `Default`, and all of my types operate on references with private types that cannot derive `Default`. I did find a crate which allows me to do this though.

```rust
#[derive(new, Setters)]
pub struct PatchReq<'a> {
    /// The client to the HAL API
    #[setters(skip)]
    hal: &'a Hal,

    /// The HAL endpoint which is being requested.
    #[setters(skip)]
    path: &'a str,

    /// The payload that is being sent to HAL.
    #[setters(skip)]
    body: String,

    /// The accept header, which will typically be a JSON response
    #[new(default)]
    #[setters(strip_option)]
    accept: Option<&'static str>,
    
    /// The content type, which will also be JSON if we send JSON
    #[new(default)]
    #[setters(strip_option)]
    content_type: Option<&'static str>,

    /// Signifies that the body contains sensitive information that must not be logged.
    #[new(default)]
    secret: bool,
}
```
