### ISSUE TITLE
Support field flattening

### ISSUE THREAD

**Issue by ryankurte** [colin-kiegel/rust-derive-builder#141]
Thanks for making a super useful library! I was wondering whether you've considered supporting flattening of fields (like [structopt](https://docs.rs/structopt/0.2.14/structopt/#flattening) does)?

I'd love to open a PR but proc macros are well outside of my comfort zone and I don't currently have the time to sink into it, so an issue will have to do for now.

Thanks,

Ryan

**Comment by TedDriggs** [comment]
I'm not sure this would be possible without pretty substantial changes. I don't know if we'd be able to get the field names from the inner struct to expose the right methods on the outer struct.

**Comment by ryankurte** [comment]
yeah it does seem like it might take some refactoring / a bit of work. seems to work for structopt though, so should be possible, if probably not worth it for now.

**Comment by ryankurte** [comment]
ahh, right, i see the difference. thanks for the response ^_^
