### ISSUE TITLE
(Feature Request) impl "builder" method for deriving type

### ISSUE THREAD

**Issue by mankinskin** [colin-kiegel/rust-derive-builder#147]
Whenever I wrote my own builders, I always found it very handy to implement a `builder` method for the type I was writing the builder for.

The advantage is that you don't really need to use the `*Builder` type directly, but can get to all of the interface from the relevant type. Also, the builder method can take values itself to construct the builder, as opposed to the Default trait. This makes it possible to have required fields, which can not have default values.

I have not used this crate much, but I did not find a way to define mandatory fields in the builder.
What I look for is something like this
```
#[derive(Builder)]
struct Entry {
    #[builder(required)]
    id: String,
    description: String,
}

fn main() {
    let entry = Entry::builder("my_entry") // required values
                               .description("This is MY entry.")
                               .build();
}
```

**Comment by TedDriggs** [comment]
This seems to be two separate requests:

1. Add a way for `#[derive(Builder)]` to generate an inherent method on the base struct which returns a builder.
2. Add a way to require that the builder take certain arguments when first created.

The first item has been previously discussed as a means of reducing the import surface for a type with an associated builder: See #73 for that conversation.

The second item has come up before - see #56 or #109 as examples.

I don't think this particular issue changes any of those conversations, so I'm going to close these issues and encourage the conversation move there.
