### ISSUE TITLE
Apply darling-style crate refactor

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#155]
The current implementation of `derive_builder` exposes too much of the crate's internal behavior across the boundary between `derive_builder` and `derive_builder_core`. This results in unnecessary minor version bumps, as seen in #154.

**Comment by TedDriggs** [comment]
@andy128k I think this would address my angst about the no_std case. `darling` borrows from `serde` and exports the types that it needs from `darling`, reexporting the proc macros from `darling_macro`. That was dtolnay's guidance on how to use one path to get those items, whether the calling code uses `core` or `std`

**Comment by andy128k** [comment]
@TedDriggs not sure if I got you. 

Module `options` is private. `derive_builder` doesn't expose it. Simple test like this #173 proves it.

**Comment by TedDriggs** [comment]
@andy128k the `darling` style refactor would combine `derive_builder_core` and the options handling of `derive_builder` into a single crate which exposed functions for operating on token streams as its only public exports. Those would then be used by `derive_builder_macro` to have a proc-macro-exporting crate. The `derive_builder` crate would reexport the proc macro, but would then be able to export more things too. We'd use that ability to have extra exports to re-export the things from `std`/`core` that `derive_builder` depends on, ensuring they'll always be available and point to the types we think they point to.

Check out the contents of [this file](https://github.com/TedDriggs/darling/blob/master/src/lib.rs) for an example.
