### ISSUE TITLE
Option to generate setters on derived struct instead of separate builder struct

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [colin-kiegel/rust-derive-builder#157]
Taking a quick look at this crate, it generates a separate `FooBuilder` for the `Foo` struct you've derived. However that does not fit my use case, where I don't want to build to a structure. I'd like to add the setters onto the structure I am deriving directly.

My use case is creating a builder that implements `amethyst::core::bundle::SystemBundle`, where the build method does not create a new object but rather registers a bunch of things with an existing World object. I see the `#[builder(build_fn(skip))]` attribute for making my own build function, but it still generates an extra useless structure.

Other use cases could be generating a builder for a structure in a foreign crate, or for an FFI object.

**Comment by ColonelThirtyTwo** [comment]
Actually now that I think about it, having the target structure around would still be useful as a container of the finalized values (ie not wrapped in Option). Though I don't see a way to rename the builder struct to anything other than `FooBuilder`.

**Comment by TedDriggs** [comment]
Renaming should be supported using `#[builder(name = "...")]` ([source](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/src/options/darling_opts.rs#L257))
