### ISSUE TITLE
Avoid the need for unwrap

### ISSUE THREAD

**Issue by Ekleog** [colin-kiegel/rust-derive-builder#163]
Hello,

I had thought for a bit about how to make a macro that'd derive builder patterns automatically, but never got to it, and it looks like you did it, and it looks great!

That said, there is one idea I think I could pass on to you: using the type system to avoid the need for the `.unwrap()` at the end after `.build()`.

This would be done by having the following process for instance, for a type `Foo` with parameters `a`, `b`, `c` and `d` (with `d` having a default value):
- There are two types defined: `Set` and `Unset`
- `FooBuilder::default()` returns `FooBuilder<Unset, Unset, Unset>`
- `FooBuilder::a(_)` is defined on `FooBuilder<A, B, C>` and returns `FooBuilder<Set, B, C>`
- `FooBuilder::b(_)` is defined on `FooBuilder<A, B, C>` and returns `FooBuilder<A, Set, C>``
- `FooBuilder::c(_)` is defined on `FooBuilder<A, B, C>` and returns `FooBuilder<A, B, Set>`
- `FooBuilder::build()` is defined only on `FooBuilder<Set, Set, Set>` (`d` not being an issue, as it has a default value it is not in the type arguments)

This way, the type system would enforce that the calls are correctly all done before the `.build()`, thus avoiding the need for the `.unwrap()`.

The downside of this approach is that it no longer is possible to eg. make a loop that reads a configuration file and sets the builder arguments one after the other. Now, I have until now only ever seen the builder pattern used in a single method-call-chain, so I don't think it'd be a big issue.

What do you think about this idea?

Cheers,
  Leo

**Comment by FSMaxB-dooshop** [comment]
You mean like https://crates.io/crates/typed-builder ? In my opinion there is an argument for having both a library that does everything at compile time and one that does it at runtime.

**Comment by Ekleog** [comment]
Indeed, I hadn't noticed it. Thank you! And I totally agree, typed-builder certainly has the downside that I listed, and thus derive_builder certainly will fit this segment :)
