### ISSUE TITLE
Idea: builder specific state and hooking into build()

### ISSUE THREAD

**Issue by jgarvin** [colin-kiegel/rust-derive-builder#167]
I ran into a situation where I have an outer object that contains inner objects. I don't want it to be possible to construct an inner type object without registering it with the outer object, but I also want to use the builder pattern. What I would like to do is make it so that you call a method on the outer object it returns an inner object builder, and then when a build successfully completes for a method on the outer object to be automatically called giving it the completed object. There are two reasons I can't currently do this with derive_builder:

* The inner objects don't have a reference to the outer object, so the inner object builder doesn't have a reference to the outer object either. Basically I need a way to make it so that the builder takes a constructor argument and saves an outer object mutable reference that will be used after build() happens.

* There is no way for me to customize the builder to cause additional actions to happen when build() is called (AFAICT.. new to Rust so maybe there is?).

**Comment by jgarvin** [comment]
I thought about this a little more and almost had a solution but ran into a new snag.

I could make an InnerWrapperBuilder struct containing a reference to Outer and an instance of InnerBuilder, and implement Deref so that InnerBuilder methods would effectively be "inherited" and then shadow the build() method with my own implementation that calls the InnerBuilder::build() and then passes the result to Outer::register(inner). I believe this would work except that users would still be able to manually dereference InnerWrapperBuilder, retrieving the underlying InnerBuilder, and then calling the unshadowed version of build(). If I could change the visibility of build to be pub(crate) I would consider that sufficient protection but I don't think the macro gives me a way to do that?

**Comment by TedDriggs** [comment]
How are you handling the lifetimes here?

**Comment by jgarvin** [comment]
@TedDriggs that is an excellent question,  I am new enough to Rust that I didn't think that part through but say we go with what I said originally -- the outer object method to get the builder would have to take &mut self in order to give &mut self to the inner object builder -- then when build was called the inner object builder would call outer.build_callback(). Then the inner object builder would go out of scope and outer wouldn't be mutably borrowed anymore. Maybe that's onerous if people hold on to builders for long periods? All the uses I've looked at construct and use immediately so by the time you want to build another inner object the old builder has already gone.

**Comment by TedDriggs** [comment]
I think this may be something you need to implement by hand; supporting this would require substantial changes across much of this crate to support the mixed-paradigm-and-custom-build logic described here.
