### ISSUE TITLE
Setters without any prefix?

### ISSUE THREAD

**Issue by anp** [colin-kiegel/rust-derive-builder#168]
I have a crate where setters make the most sense with no prefix at all. Would you be interested in a PR to implement `#[builder(setter(prefix = false))]` or similar?

**Comment by TedDriggs** [comment]
Based on [this line](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/src/options/darling_opts.rs#L459), I think this should work if you just omit `prefix` outright.

**Comment by anp** [comment]
Aha! I must have misunderstood the documentation, but looking again and it's quite clear: https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/src/lib.rs#L190. Thanks :D
