### ISSUE TITLE
Delegate builder member-function

### ISSUE THREAD

**Issue by windy1** [colin-kiegel/rust-derive-builder#176]
A common convention in the builder pattern is to define a delegate function in builder's target type. For example:

```rust
#[derive(Builder)]
struct Fruit {
    name: String,
    color: String,
}

impl Fruit {
    pub fn builder() -> FruitBuilder {
        FruitBuilder::default()
    }
}
```

I personally prefer this over instantiating the builder directly because it makes for a more fluent interface. Additionally, you can avoid `use`ing the builder at all. It would be nice to derive such a function automatically. Perhaps:

```rust
#[builder(delegate_function)]
```

Thank you for your work on this project - I use it for nearly everything! <3

**Comment by TedDriggs** [comment]
I believe there's some additional complexity that comes from type parameters, but in principle I'm not opposed to this. That said, I do wonder how much value there is from it, since the function itself is so lightweight and won't change when the builder changes.

Do you write doc comments for your `builder` method, or is it usually self-explanatory?

**Comment by windy1** [comment]
@TedDriggs Thanks for your reply. Typically I would not write documentation for such a function but, then again, I don't write much documentation at all (lol). This would be a quality-of-life upgrade - obviously it's quite trivial to write the function out yourself, but if you follow this pattern then having it be derived instead would make things more concise.

Again, this is a very common pattern that I've seen often - it's not just my personal preference I'm going on. Google, for instance, employs this pattern in many of it's APIs.

**Comment by TedDriggs** [comment]
> I don't write much documentation at all (lol)

Hah, well at least you're honest; some of us just like to imagine we're writing useful docs.

> Again, this is a very common pattern that I've seen often

Same. I actually thought about implementing this before, but hit two problems:

1. `derive_builder` would now have to make another `impl` block for the input struct to put this method. Separate `impl` blocks show up separately in rustdoc, and I actually found having the builder method in its own section of the docs to be more irritating than typing this one function out.
2. I think there's some complexity around type parameters, but I know `syn` tries to make that easy so maybe I'm incorrect on this point.

**Comment by windy1** [comment]
> Separate impl blocks show up separately in rustdoc

I've never noticed that. Just tried it out and I see what you mean. I agree that's quite irritating. Perhaps it could be abstracted into a trait?

Consider the following (naive) example:

```rust
struct Test {}
struct TestBuilder {}

impl Test {
    /// Test 1
    fn test1() {}
}

trait BuilderDelegate<T: Default> {
    /// Creates a new default builder for type `T`
    fn builder() -> T {
        T::default()
    }
}

impl Default for TestBuilder {
    fn default() -> TestBuilder {
        TestBuilder {}
    }
}

impl BuilderDelegate<TestBuilder> for Test {}

fn main() {
    let builder: TestBuilder = Test::builder();
}
```

Which produces the docs:

![image](https://user-images.githubusercontent.com/755713/93382296-f2454a00-f82f-11ea-9b35-4f25902b2d4e.png)

**Comment by nkconnor** [comment]
if it is abstracted out into a trait then the end-user has to import the trait.. which, for me, defeats the motivation. The only reason I want `::builder()` is so that I have one less import to deal with. Most of the time I have to import `{X, XBuilder}`

**Comment by TedDriggs** [comment]
Given how small the function is here (and how infrequently it needs to change), I'm closing this out.
