### ISSUE TITLE
todo: test with multiple versions of custom_derive

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#18]
We can not control which version of custom_derive is used by a client of this crate.

Just to be save, we should test with multiple versions of custom_derive. It would be sufficient if these tests only run on travis.

However I'am not sure, about the best way to achieve this.

* it seems like dev-dependencies can't be opted out of
* optional dependencies are fixed to a specific version
* cargo features may only specify optional dependencies

http://doc.crates.io/manifest.html

One hacky approach might be usage of `sed 's/placeholder/version/g'` on a Cargo.toml template before `cargo test`.

**Comment by colin-kiegel** [comment]
suggestions are welcome. :-)

**Comment by killercup** [comment]
At first, I would not check for this at all, but just mention in the Readme what version we are currently running tests with.

And when the first bug reports that are caused by a breaking change in custom_derive, I would make that part of the Readme bold. 😉

But seriously, this is basically impossible to solve without cargo supporting something like npm's peer-dependencies.

**Comment by colin-kiegel** [comment]
I just realized, the latest version of custom_derive is still 0.1.5 so there haven't been any breaking changes, yet.

But in case this becomes relevant, I just solved it with a really simple bash script, which loops over some arrays and then does
```
cargo add $crate@$version --dev
cargo update
cargo test
```

I think we could just commit such a script to our repository and make travis run it. But since it is not relevant _now_, I saved it as a gist for future use - voilà ;-)
https://gist.github.com/colin-kiegel/ea4f13db5b14374c68ed345a2224f990

**Comment by colin-kiegel** [comment]
PS: On second thought we could also use travis env-variables
https://docs.travis-ci.com/user/environment-variables/#Global-Variables

This way all combinations would result in a different run (definitely slower, but better visualisation in travis)
