### ISSUE TITLE
Support for running without alloc?

### ISSUE THREAD

**Issue by smmalis37** [colin-kiegel/rust-derive-builder#181]
Would it be possible to improve the no_std support to not require alloc? I know one breaking change would be changing the signature of the generated .build to not return a String in the error case, but in my current project all of these seem to be able to be switched to &'static str with no issues (according to cargo-expand). I'm not sure what other changes would be needed, or if there are error cases that can't be static strs.

**Comment by TedDriggs** [comment]
I think on master we now only allocate for the custom error case. I'm not 100% sure how we'd address that, but I'm open to suggestions.
