### ISSUE TITLE
Allow specification of custom error type

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#191]
Crates may already have an error into which they'd like to feed builder failures. Add `#[builder(build_fn(error = "..."))]` to allow specifying that, and document the contract for that custom error type.

**Comment by andy128k** [comment]
Alternatively a simpler solution is possible. Just allow to make `build()` method and error type private.

```rust
#[derive(Builder)]
#[builder(error(private))]
#[builder(build_fn(name = "build_impl", private))]
struct Lorem {
    pub ipsum: u8,
}

impl LoremBuilder {
    pub fn build(&self) -> Result<Lorem, CustomError> {
        self.build_impl()
            .map_err(|private_lorem_builder_error| CustomError::new(... private_lorem_builder_error...))
    }
}
```
