### ISSUE TITLE
Idea: Allow custom validation errors

### ISSUE THREAD

**Issue by andy128k** [colin-kiegel/rust-derive-builder#193]
Current implementation of an VaidationError stores a `String`. This forces users to convert errors to a string makes analyzing of custom errors hard.

ValidationError's definition can be changed from ValdationError(String) to ValdationError(Box<dyn std::error::Error>). The drawback of such change is that `std::error::Error` is not supported in `no_std`.

**Comment by TedDriggs** [comment]
This is where a custom error type would be useful; the way we emit the error in the validation case would allow for that function to return `impl Into<BuildFnError>`, and allowing the caller to tell us which error type to use would solve that. See #191 for this.

**Comment by andy128k** [comment]
#194 Solves this issue.
