### ISSUE TITLE
Custom builder function for specific field

### ISSUE THREAD

**Issue by mmiecz** [colin-kiegel/rust-derive-builder#197]
Hello, I've found your crate recently, and I'm finding it awesome!

I have some question about such scenario:

```
struct Header {
    frame_type: u8,
    frame_len: u8,
}

struct Frame {
    header: Header,
    payload: Vec<u8>
}
```
I want to have a FrameBuilder derived, and be able to update `frame_len` field, while adding `payload` data. Is there any way to do so? 

Thanks!

**Comment by TedDriggs** [comment]
I think you could use `#[builder(setter(skip))]` on the two fields and then implement a setter yourself.
