### ISSUE TITLE
Using default generic parameter types for skippable fields

### ISSUE THREAD

**Issue by srithon** [colin-kiegel/rust-derive-builder#198]
In a project I'm working on, I have an immutable buildable struct that contains an optional generic field. When this field is not set, the compiler throws an error because it cannot infer its type.

However, since the struct is immutable, this field would stay `None` forever, meaning that its corresponding type would not be relevant. I attempted to fix this by giving it a [Default Generic Type Parameter](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#default-generic-type-parameters-and-operator-overloading) with a throwaway type, but it did not work as I expected.

This is a minimal example of the issue.

I set the placeholder type to `Vec<String>` because in my project the type of `B` has bounds which prevent it from being `()`.

```rust
use derive_builder::Builder;

#[derive(Builder)]
struct GenericStruct<A, B = Vec<String>> {
    required_field: A,

    #[builder(setter(strip_option), default)]
    optional_field: Option<B>
}

fn main() {
    let a = GenericStructBuilder::default()
        .optional_field(30)
        .required_field("hello")
        .build();

    // **Error**
    let b = GenericStructBuilder::default()
        .required_field("hello")
        .build();
}
```

```
error[E0282]: type annotations needed for `std::result::Result<GenericStruct<&str, B>, String>`
  --> src/main.rs:18:13
   |
18 |     let b = GenericStructBuilder::default()
   |         -   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `B` declared on the struct `GenericStructBuilder`
   |         |
   |         consider giving `b` the explicit type `std::result::Result<GenericStruct<&str, B>, String>`, where the type parameter `B` is specified
```

## Potential User Workarounds

1. Remove `strip_option` and `default`, and make users explicitly pass in `Option::<()>::None` to the setter
2. Something with Box?

## Potential Crate Solutions

1. Internally use workaround #1 before `build()` to set the type

## Other Notes

- I tried plugging in the [`default_type_parameter_fallback` feature gate](https://github.com/rust-lang/rust/issues/27336), but could not get it to work
- I also tried specifying `default = "Option::<Vec<String>>::None"`, but that didn't work

## Resources

- [Manual Builder Solution](https://stackoverflow.com/questions/37310941/default-generic-parameter) (without `derive_builder`): stackoverflow post asking about a similar situation
- [0213-defaulted-type-params RFC](https://github.com/rust-lang/rfcs/blob/master/text/0213-defaulted-type-params.md)
- [Type inference fails in light of generic type aliases with default parameter. #50822](https://github.com/rust-lang/rust/issues/50822): GitHub issue for Rust
- [Default generic type inference](https://www.reddit.com/r/rust/comments/ek6w5g/default_generic_type_inference/): reddit post

**Comment by TedDriggs** [comment]
I'm not sure there's anything this crate can do, I'm afraid.
