### ISSUE TITLE
Should builder methods use `mut self` or `&mut self`?

### ISSUE THREAD

**Issue by killercup** [colin-kiegel/rust-derive-builder#2]
I haven't put much thought into it. @colin-kiegel wrote earlier (roughly translated):

> IMHO, setter methods should take `mut self` instead of `&mut self`. This is more restricting, but in has two advantages—it allows us to write:
> 
> ```rust
> Channel::default()
>     .token(raw_token)
>     .into<X>();
> ```
> 
> 1. `Channel::default()` needn't be bound to anything. Without the move into the setter methods it would be out-of-scope too soon.
> 2. It's possible to call the final `into<X>` (and similar methods) without `.clone()`

**Comment by colin-kiegel** [comment]
my vote for: `mut self`

I can not see a practical use case for `&mut self`. And if there really is, there still might be a 50%-chance that clone() is sufficient for going from `&(mut) self` to `mut self`..

**Comment by killercup** [comment]
FYI, #4 uses `mut self`.

We could also offer an immutable/persistent version (like `#[derive(Builder(persistent))]`) for smaller structs where all setter methods are just
```rust
fn foo<V: Into<Foo>>(&self, value: V) -> Self {
    Self { foo: value.into(), ..*self }
}
```

(I'm pretty sure that clones all fields except for foo).

**Comment by colin-kiegel** [comment]
I was going to link this in the readme and found it addresses the difference between consuming vs. non-consuming builder pattern:
* https://aturon.github.io/ownership/builders.html

Benefit of consuming builder pattern:
* terminal method receives ownership

Benefit of non-consuming builder pattern:
* complex configuration is more convenient (i.e. when you don't chain the calls)

**Comment by killercup** [comment]
As it says "Non-consuming builders (preferred)"—do you want to change this before our initial release?

**Comment by colin-kiegel** [comment]
I don't really share this preference, because [example/channel.rs](https://github.com/colin-kiegel/rust-derive-builder/blob/master/examples/channel.rs) will stop working, if the setter-method uses a borrow `&mut self` instead of a move `mut self`.

```
examples/channel.rs:33:14: 33:32 error: borrowed value does not live long enough
examples/channel.rs:33     let ch = Channel::default().special_info(42);
                                    ^~~~~~~~~~~~~~~~~~
examples/channel.rs:33:50: 35:2 note: reference must be valid for the block suffix following statement 0 at 33:49...
examples/channel.rs:33     let ch = Channel::default().special_info(42);
                                                                        ^

examples/channel.rs:33:5: 33:50 note: ...but borrowed value is only valid for the statement at 33:4
examples/channel.rs:33     let ch = Channel::default().special_info(42);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/channel.rs:33:5: 33:50 help: consider using a `let` binding to increase its lifetime
examples/channel.rs:33     let ch = Channel::default().special_info(42);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I am still convinced the preferred builder pattern should be the consuming one to support the one-line pattern. I filed an issue for the documentation here https://github.com/aturon/aturon.github.io/issues/5

@killercup in the meantime - shall we keep a (less prominent) link to this article anyway, or avoid it to prevent confusion?

**Comment by colin-kiegel** [comment]
My suggestion would be to put this at the bottom of the readme for now:

The builder pattern is explained [here][builder pattern]. But please note that there is a [debate](https://github.com/aturon/aturon.github.io/issues/5) about which variant is preferrable for what reasons.

[builder pattern]: https://aturon.github.io/ownership/builders.html

**Comment by killercup** [comment]
Makes sense, and sounds good. 👍

(This is the 'official' rust style guide, right? I think that was moved to
docs.rust-lang.org/style but recently removed there because it didn't get
enough exposure and is still basically full of todos.)


Colin Kiegel <notifications@github.com> schrieb am So. 7. Aug. 2016 um
13:02:

**Comment by colin-kiegel** [comment]
Ok, I was wrong about https://github.com/aturon/aturon.github.io/issues/5 and you argued that most clones get optimized away. I'd like to verify the Clone is really removed, then we can switch to &mut.

But with some hint that people like me don't need to worry about unnecessary cloning.

**Comment by colin-kiegel** [comment]
Ok I had a look at the most simple example and made a comparison of source code, MIR, LLVM IR, and ASM.
```rust
fn main() {
    let ch = Channel::default().special_info(42).build();
    black_box(ch);
}
```

https://gist.github.com/colin-kiegel/85d6659da34f34e9e133fc0d9767152f/revisions

1. revision is `&mut self`
-  revision is `self`

good news: the final ASM is identical. This first test was only on nightly now (because of MIR), but it looks promising.

Let's try to find some examples which might be harder to optimize for llvm - what could it be? Next thing I would try would be passing the builder around (e.g. into functions which act on the builder).

If we can't beat the optimizations without too much effort, then I would feel perfectly good about switching to `&mut self`. :-)

**Comment by colin-kiegel** [comment]
Ok, another try to confuse the compiler using disjunct modules and some clones in `foo::a-c`

```rust
fn main() {
    let mut builder = builder::Channel::default();
    
    builder = foo::a(builder, 1);
    builder = foo::b(builder, 2);
    builder = foo::c(builder, 3);
    
    let ch = builder.build();
    black_box(ch);
}
```

https://gist.github.com/colin-kiegel/7aaf4ec60aff8ace360457f96ffc5e02/revisions

Again the ASM is the same - this time compiled with stable. Next step would be to put the builder definition in a separate crate. From what I have read once, disjunct crates can indeed break some optimizations.

IMO this would be the last hoop to take. I'll try that another day. :-)

**Comment by colin-kiegel** [comment]
switched to non-consuming pattern `&mut self` with [v0.2.0 (Changelog)](https://github.com/colin-kiegel/rust-derive-builder/blob/master/CHANGELOG.md#020---2016-08-22)

**Comment by jun-sheaf** [comment]
Using trivially copyable types for testing optimization is probably not indicative.

The following link uses a simple builder with `&mut self`

 - https://godbolt.org/z/8j6KT4GEe

Using `self`, you get optimized code:

 - https://godbolt.org/z/968rrKex8

**Comment by TedDriggs** [comment]
@jun-sheaf you may well be right about the performance characteristics, but the library isn't going to change its default pattern after 8 years in the wild. If you'd like to submit a PR that updates the documentation to show a comparison of the generated code's efficiency, that would be welcome.
