### ISSUE TITLE
Release of 0.10

### ISSUE THREAD

**Issue by petrosagg** [colin-kiegel/rust-derive-builder#200]
Hey @colin-kiegel! I was going through some crate updates and noticed that there is a pending 0.10 release of derive_builder with updated dependencies. Do you have any rough estimate as to when this is going to go out of alpha?

Some preliminary testing I did on my side didn't produce any issues :)

**Comment by TedDriggs** [comment]
This will go out either this week or early next week. We've had it in alpha for a while because the changes to errors were substantial, but at this point I don't think we'll get more feedback until we push 0.10.0 to the world.

**Comment by petrosagg** [comment]
That sounds great, thank you!

**Comment by TedDriggs** [comment]
It's published.
