### ISSUE TITLE
README example code is outdated

### ISSUE THREAD

**Issue by tv42** [colin-kiegel/rust-derive-builder#211]
"How it Works" example has

```
#[macro_use]
extern crate derive_builder;
```

which is old style Rust and not very recognizable/usable to newbies (https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html).

Below it, "Get Started" says "Add `use derive_builder::Builder;`", which is the new style.

**Comment by TedDriggs** [comment]
This relates to #231; I think we want to move all the tests and examples to the new style.
