### ISSUE TITLE
[Feature Request] Add boolean setter to set `bool` by simple method call

### ISSUE THREAD

**Issue by jquesada2016** [colin-kiegel/rust-derive-builder#218]
Reading through the docs, I did not see if this was already possible, but it would be very convenient to be able to (un)set a `bool` field a simple method call. Let's take the following.

```rust
struct MyStruct {
  true_bool: bool,
}
```

It would nice to do the following:
```rust
// This
MyStructBuilder::default().true_bool().build();

// Instead of this
MyStructBuilder::default().true_bool(true).build();
```

And in the cases where a false bool should be set, perhaps:
```rust
#[derive(Builder)
struct MyStruct {
  #[builder(setter(bool = "false") // could also be "false/true" to allow for either setting or unsetting
  bool_field: Option<bool>
}

// The #[builder(setter(bool = "true")] case
MyStructBuilder::default().set_bool_field().build();

// The #[builder(setter(bool = "false")] case
MyStructBuilder::default().unset_bool_field().build();

// The #[builder(setter(bool = "true/false")] case
MyStructBuilder::default().set_bool_filed().unset_bool_field().build();
```

**Comment by TedDriggs** [comment]
You can add inherent methods of your own to the builder using an additional `impl` block; I'd suggest doing that for this case. The character savings otherwise are too small to justify the added complexity for the macro.
