### ISSUE TITLE
(too niche?) Custom build method / pub(crate) builder methods

### ISSUE THREAD

**Issue by blagovestb2c2** [colin-kiegel/rust-derive-builder#219]
Hello,

I am wondering if i can fit this crate into my use case. Essentially, i am in a situation where i have an enum 

```rust
pub enum Variants {
   Variant1(Data),
   Variant2(Data),
   Variant3(Data),
}
```

where the `Data` struct has the same fields, but the values satisfy different invariants for each of the variants.

Ideally, i'd like the interface to be something like

```
VariantsBuilder::default().data_field1(..).data_field(2)...variant3()
```

I could leverage this crate if i put a builder on `Data`, but then i have two problems:

1. the builder constructs Data which i want to be read-only for the outside world
2. there is no way for me to hide some fields from the builder and only set them based on the build method called (i.e. `variant1`, `variant2`, `variant3`)

A possible solution would allow me to mark certain builder methods as pub(crate), including `build`, and i will then expose additional methods via an impl block on the Builder that will set them everything per the requirement. Is there a way to do this right now? Can it be added?

Extra points if I could control the name of the Builder/BuilderError structs too.

**Comment by blagovestb2c2** [comment]
i found out about builder(skip_fn). sorry, i might have been too quick to post

**Comment by TedDriggs** [comment]
You can make `DataBuilder::build` private using `#[builder(build_fn(private))]`. You'd then expose your public variant-specific methods and have those internally call `DataBuilder::build()` and do their checks on the results.

That said, I feel obliged to point out that as-written nothing stops someone from taking a variant-2 `Data` and putting it into `Variant3`. Your code may have other ways of doing this (e.g. use of `#[non_exhaustive]`) but enum fields are not private.
