### ISSUE TITLE
bors-ng integration

### ISSUE THREAD

**Issue by badboy** [colin-kiegel/rust-derive-builder#22]
Moving discussion from #20 here:

Documentation is at http://homu.hellorust.com/
Authorized is whoever I put into the list.
This is all pretty manual right now (someday I will be as dynamic as homu.io)

Now to the sad part: It seems I would actually need owner rights to modify the right hooks, and I don't think you can give this to others on a user repository (only on organization repository).

So for now the integration has to wait until I figure out a way for you to execute this (or inserting the right hooks manually)

**Comment by killercup** [comment]
@badboy you have a competitor! ;)

I have some invites for https://aelitabot.xyz/ which basically the same thing, but written in Rust and with a worse name IIUC.

**Comment by colin-kiegel** [comment]
[aelitabot.xyz](https://aelitabot.xyz/) is shutting down on 2017-03-06. The maintainer recommends either switching to [bors-ng](https://bors-ng.github.io/) or self-hosting.

**Comment by badboy** [comment]
I have an instance of bors-ng running at http://not-a-robot.herokuapp.com/. I could open it up to others

**Comment by badboy** [comment]
So, not-a-robot is back up and updated and public. If you still want it can be added here.

**Comment by killercup** [comment]
FYI I have several repos using https://bors-ng.github.io now, works like charm

**Comment by badboy** [comment]
Yup, it's basically the same, use what suits you best

**Comment by Dylan-DPC** [comment]
@TedDriggs nah, it isn't overkill. Using bors on other crates and it is fine for this one
