### ISSUE TITLE
Builder with all const methods

### ISSUE THREAD

**Issue by songzhi** [colin-kiegel/rust-derive-builder#220]
Since [const_panic](https://github.com/rust-lang/rust/pull/89508) is stablized, I guess it's easy to generate a Builder with all const methods? At least for the simple structs.

**Comment by TedDriggs** [comment]
How would this interact with existing builder and setter options? Would this be a new builder pattern, alongside `owned`, `immutable`, etc?

**Comment by TedDriggs** [comment]
In the absence of a use-case for this (and the complexity that seems likely as this interacts with other builder settings) I'm closing as "Won't Do"
