### ISSUE TITLE
Generate `builder` method on the target struct

### ISSUE THREAD

**Issue by stoically** [colin-kiegel/rust-derive-builder#223]
I'm almost always adding a `builder` method to the target struct, like e.g.

```rust
#[derive(Debug, Builder)]
struct Something {
  field: String,
}

impl Something {
  pub fn builder() -> SomethingBuilder {
    Default::default()
  }
}
```

Would be useful to have derive-builder generate it for me.

**Comment by TedDriggs** [comment]
This is discussed [here](https://github.com/colin-kiegel/rust-derive-builder/issues/170#issuecomment-665087279); given the relatively small savings, and the impact on how the struct will present in documentation, I’m disinclined to add it.

**Comment by stoically** [comment]
Thanks for the pointer. I guess that makes sense. Tho the idea to have an attribute for `#[builder()]` might be nice. Maybe something like `builder_fn`.
