### ISSUE TITLE
Setter prefix / Option<> setters?

### ISSUE THREAD

**Issue by matthiasbeyer** [colin-kiegel/rust-derive-builder#24]
Hi,

I'm not sure whether such a thing is possible, but I like to prefix my setters with `with_`, so I have:

``` rust
Foo::new()
    .with_bar(42)
    .with_baz("foofoo")
    .with_something(Else::new())
```

And if there is a field which is an `Option<>` I also like to have the `without_*` functions, so I can effectively:

``` rust
Foo::new()
     .with_bar(42) // sets `self.bar = Some(42)`
     .without_bar() // sets `self.bar = None`
```

is such a thing possible?

**Comment by killercup** [comment]
Sadly, stable macros can't be used to create new identifiers (method names)
right now. See also the ticket for getters.

Hopefully this will be possible soon, though!

Matthias Beyer <notifications@github.com> schrieb am Di. 23. Aug. 2016 um
15:41:

**Comment by colin-kiegel** [comment]
Hi matthias, thank you for your feedback. :-)

You can use this workaround for now:
* name your fields like you want to have the setter methods, i.e. "with_bar: i32" etc.

And as soon as procedural macros are stabilized we can think about this kind of stuff. Probably within a couple of months. :-)

Outlook:
For backwards compatibility we will probably make these opt-in modes. I could imagine something like this:
* `#[derive(Builder(prefix=with, option=implicit))]`

**Comment by colin-kiegel** [comment]
Or something more compact?
* `#[derive(Builder(fluent))]` => handle Options as suggested above and use prefixes `with` / `without` by default
* `#[derive(Builder(fluent=(set,unset)))]` => use prefixes `set` / `unset` instead

**Comment by colin-kiegel** [comment]
with [v0.3.0](https://github.com/colin-kiegel/rust-derive-builder/releases/tag/v0.3.0) we have most of what you want
* custom setter prefixes
* builder struct internally works with `Option`

please open a new ticket if you think that you still need _un_-setters like `without_foo()` or something else. Thanks.
