### ISSUE TITLE
BuilderErrors derived with derive_builder do not have `PartialEq` nor `Eq` derived

### ISSUE THREAD

**Issue by EvanCarroll** [colin-kiegel/rust-derive-builder#256]
I'm wrapping the error generated by derive_buidler. The error wrapper that I'm creating derives `Eq` and `PartialEq`: it needs to derive those traits because my test suite is built by testing things that throw an error and using `assert_eq!()` to test that the error I got back is the same as the error I'm expecting. Because my wrapper error derives `Eq` and `PartialEq`, I get this error when I try to include the Error struct that derive_builder generates,

```
error[E0277]: the trait bound `ElementBuilderError: Eq` is not satisfied
   --> src/error.rs:21:3
    |
5   | #[derive(Debug, Eq, PartialEq, Error)]
    |                 -- in this derive macro expansion
...
21  |         source: crate::element::ElementBuilderError,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Eq` is not implemented for `ElementBuilderError`
    |
note: required by a bound in `AssertParamIsEq`
   --> /home/ecarroll/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:316:31
    |
316 | pub struct AssertParamIsEq<T: Eq + ?Sized> {
    |                               ^^ required by this bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `ElementBuilderError` with `#[derive(Eq)]`
    |
6   | #[derive(#[derive(Eq)]
    |          +++++++++++++

error[E0369]: binary operation `==` cannot be applied to type `ElementBuilderError`
  --> src/error.rs:21:3
   |
5  | #[derive(Debug, Eq, PartialEq, Error)]
   |                     --------- in this derive macro expansion
...
21 |         source: crate::element::ElementBuilderError,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: an implementation of `PartialEq<_>` might be missing for `ElementBuilderError`
  --> src/element.rs:6:10
   |
6  | #[derive(Builder, Clone, Debug, PartialEq, Eq)]
   |          ^^^^^^^ must implement `PartialEq<_>`
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `ElementBuilderError` with `#[derive(PartialEq)]`
   |
6  | #[derive(#[derive(PartialEq)]
   |          ++++++++++++++++++++

error[E0369]: binary operation `!=` cannot be applied to type `ElementBuilderError`
  --> src/error.rs:21:3
   |
5  | #[derive(Debug, Eq, PartialEq, Error)]
   |                     --------- in this derive macro expansion
...
21 |         source: crate::element::ElementBuilderError,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: an implementation of `PartialEq<_>` might be missing for `ElementBuilderError`
  --> src/element.rs:6:10
   |
6  | #[derive(Builder, Clone, Debug, PartialEq, Eq)]
   |          ^^^^^^^ must implement `PartialEq<_>`
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `ElementBuilderError` with `#[derive(PartialEq)]`
   |
6  | #[derive(#[derive(PartialEq)]
   |          ++++++++++++++++++++

lEq<_>`
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `ElementBuilderError` with `#[derive(PartialEq)]`
```

Here is an example of the code that does **NOT** work, notice the `PartialEq` and `Eq`

```rust
#[derive(Debug, Error, PartialEq, Eq)]
pub enum SequenceError {
	#[error("An error occured in building an Element")]
	ElementBuilder {
		#[from]
		source: crate::element::ElementBuilderError,
	},

```

Here is an example of the code that works, notice there is no `PartialEq` nor `Eq`. I can't automatically derive them.

```rust
#[derive(Debug, Error)]
pub enum SequenceError {
	#[error("An error occured in building an Element")]
	ElementBuilder {
		#[from]
		source: crate::element::ElementBuilderError,
	},

```

**Comment by TedDriggs** [comment]
Have you tried using `#[builder(derive(PartialEq))]`? That should allow you to derive it and `Eq`

**Comment by EvanCarroll** [comment]
I've tried that on 

```rust
#[derive(Builder, Clone, Debug, PartialEq, Eq)]
#[builder(derive(PartialEq, Eq))]
pub struct Element {
	inner: u64,
	renderer: SeqRenderer,
}
```

However, the error isn't on `Element`, or `ElementBuilder`. It's on `ElementBuilderError`.

**Comment by EvanCarroll** [comment]
I've also updated the topic itself, to reflect the new information being specific to my deriving of `PartialEq` and `Eq` on a newtype that includes the error struct generated here.

**Comment by EvanCarroll** [comment]
This is where the list of traits on the error type are specified. Note currently the only trait that exists on the Error type is `Debug`

**Comment by EvanCarroll** [comment]
Looking at the code we have different options to fixing this,

1. Make it such that all BuilderErrors derive Eq, and PartialEq.
2. Make it such that all BuilderError implement the same derives as their associated Builder, this was suggested https://github.com/colin-kiegel/rust-derive-builder/issues/256#issuecomment-1144231293
3. Make it such that all BuilderError has its own derives. `#[builder( derive(Debug, PartialEq, Eq), error_derive(Debug, PartialEq, Eq) )]`

**Comment by TedDriggs** [comment]
The recommended fix would be to manually implement the error for this builder.
________________________________

**Comment by EvanCarroll** [comment]
So then we should be clear we don't support `Eq`, or `PartialEq` for the BuilderError, and that subsequently you can't test that the error you returned with `assert_eq!()`? Seems like it may be something worth noting in the docs? I can confirm adding Eq and PartialEq doesn't break anything, is there any reason why you don't like that solution? Is there any reason the BuilderError generated can't implement these by default?

**Comment by TedDriggs** [comment]
In that situation, the recommended solution would be to use your own error struct.

```rust
pub enum SequenceError {
    BuilderMissingField(&'static str),
}

impl From<derive_builder::UninitializedFieldError> for SequenceError {
    fn from(err: derive_builder::UninitializedFieldError) -> Self {
        Self::BuilderMissingField(err.field_name())
    }
}

// and then later
#[derive(Builder)]
#[builder(build_fn(error = "SequenceError"))]
pub struct YourStruct {}
```

A running example is [here](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/examples/custom_error.rs)
