### ISSUE TITLE
Support tuple structs

### ISSUE THREAD

**Issue by tupshin** [colin-kiegel/rust-derive-builder#26]
It appears that custom deriving a tuple struct does not work. Would be a very nice convenience to support those as well as regular structs.

**Comment by killercup** [comment]
How would you name the setter methods?

Tupshin Harper <notifications@github.com> schrieb am So. 28. Aug. 2016 um
18:32:

**Comment by tupshin** [comment]
Good question. I'll play with derive! a bit more and see if there is any behavior/naming that would make sense.

**Comment by tupshin** [comment]
I've got nothing. :)
Going to use a combination of derive builder and newtype_derive, along with rethinking my approach slightly. Closing, for now, at least.
