### ISSUE TITLE
Enhance support for collection types

### ISSUE THREAD

**Issue by sunng87** [colin-kiegel/rust-derive-builder#260]
A further step for supporting collection types like `Vec` or `HashMap` is to generate insertion function for its content types. This allows user to create collection in a declarative manner. 

For Example:

```rust
#[derive(Builder)]
pub struct Group {
  members: Vec<User>
}
```

Generated builder contains a function called `push_member`, by which you can 
```
builder.
  .push_member(user1)
  .push_member(user2)
```

**Comment by TedDriggs** [comment]
Have you looked at the `each` setter options?

**Comment by sunng87** [comment]
Cool. That seems to be my need. I'll do some experiment with it and come back to you later.

**Comment by sunng87** [comment]
It works! Thank you for your response.

**Comment by DontBreakAlex** [comment]
I'm sorry to dig up this issue, but has this feature been removed ?  I can't find any mention of `each` in the docs and this doesn't build:
```
error: Unexpected meta-item format `word`
  --> src/parse.rs:17:22
   |
17 |     #[builder(setter(each))]
   |                      ^^^^
   ```

**Comment by TedDriggs** [comment]
Still exists, it just doesn't support that format - that's why the error says "unexpected format" and not "unknown field"

Usage is [here](https://github.com/colin-kiegel/rust-derive-builder/blob/da455f69ed7b7c422a3fcced60b10be309697917/derive_builder_core/src/macro_options/darling_opts.rs#L231)
