### ISSUE TITLE
Custom documentation for XBuilder::build

### ISSUE THREAD

**Issue by bobbbay** [colin-kiegel/rust-derive-builder#262]
Currently, the `XBuilder::build` documentation is generated as follows:

---

Builds a new X.

#### [Errors](https://github.com/colin-kiegel/rust-derive-builder/issues/new#errors)
If a required field has not been initialized.

---

Is it possible to customize this documentation? For instance, I have a custom validation function that can fail for different reasons. I would like to mention that in my documentation.

**Comment by TedDriggs** [comment]
There's not support for changing the documentation through the macro, but it's trivial to create the effect you're looking for:

1. Add `#[builder(build_fn(private, name = "build_internal"))]` to your struct.
2. Add an inherent impl block for your builder in the same module as the deriving struct
3. Add your own `build` method that has the same signature as `build_internal`
4. Put your custom documentation on that method.

There's no reason we _couldn't_ add a macro option for this, but it would need to be written inside quotation marks so the authoring experience would be pretty rough. For that reason, I'm inclined to think this approach of wrapping the build method is probably the better solution long-term, even if it is more code.

**Comment by bobbbay** [comment]
Yeah, I'm good with that solution. It's not too overcomplicated, and makes sense. Thank you!
