### ISSUE TITLE
Can a builder have transient properties, not present in target?

### ISSUE THREAD

**Issue by dan-da** [colin-kiegel/rust-derive-builder#279]
Sometimes it is useful to have a Builder that accepts attributes which are not present in the target struct, but are used to build propert(ies).

Consider this struct:

```
struct MyData {
    json_value: json::Value,
    ...,
}
```

Now let's say we want to have a builder method that accepts json as a string, so we can say:

```
   MyDataBuilder::default().json_string(json).build()?
```

The idea here is that `::json_string(json: &str)` stores the string in a builder-specific property and then actual parsing (with possible error) is performed inside `::build()`, which has a custom impl that requires no parameters.   Only the successfully parsed result is stored in MyData.

From a brief read of the docs, I didn't see that this is possible today.  If it is, please let me know.

The only workaround I'm aware of is to accept `json` as a parameter to ::build().  While this works, it gets messy if there are many such inputs, and it feels like we are no longer using the builder pattern with a setter for each property.

I have used this pattern in my own custom builders in the past (with Builders having slightly different properties from the target struct) so I was hoping/expecting to find it here. 

Since these builders are automatically derived, it may be tricky syntactically to specify the "transient" properties in the Builder struct.  Maybe it would work to specify a "transients" helper struct.  Something like:

```
#[derive(Builder)]
#[builder(transients=MyDataBuilderTransients)]
struct MyData {
    json_value: json::Value,
    ...,
}

struct MyDataBuilderTransients {
    json_string: String,
}
```
So the derived MyDataBuilder struct would then contain a transients field, available for use by a custom `::build()`.

```
struct MyDataBuilder {
    ...,
    transients: MyDataBuilderTransients,
}
```

Well, that's one idea for an approach, anyway.

I'm presently evaluating derive_builder for use in a large existing project.  The first struct I am trying to use it for is quite large, and has a ::new() method that takes many parameters, with several of them being transients, so already I've bumped into this issue.

-----

edit: in the above trivial example, another workaround would be to use a custom "try" setter to parse json_string and set ::json_value.   However, in my real use-case, there are actually multiple dependent and inter-related properties in the target struct, so it is cleanest by far to delay any build processing until all input params are set and ::build method is called.

**Comment by TedDriggs** [comment]
I don't think you need transient fields to achieve your goal. It sounds like you actually have three structs in mind:

1. `MyData`
2. `MyDataSeed` - hand-written, private, includes all the fields that someone should be able to pass to the builder.
3. `MyDataBuilder` - this is derived from `MyDataSeed`, and conceals the existence of the seed intermediate struct from the outside world.

Here's some example code:

```rust
enum MyDataBuilderError {
    MissingField(&'static str),
    Json(serde_json::Error),
    Conflict(&'static str),
    OtherThings,
    WhateverIsAppropriate
}

impl From<derive_builder::UninitializedFieldError> for MyDataBuilderError {
    fn from(e: &derive_builder::UninitializedFieldError) -> Self {
        Self::MissingField(e.field_name())
    }
}

impl From<serde_json::Error> for MyDataBuilderError {
    fn from(e: &serde_json::Error) -> Self {
        Self::Json(e)
    }
}

pub struct MyData {
    json: serde_json::Value,
}

/// This struct will hold all the fields that go into building `MyData`, both those that have
/// a 1:1 counterpart in `MyData` and those that are "transient". 
///
/// There's no way to make the compiler ensure fields added to `MyData` are added to `MyDataSeed`,
/// but you can use the **field_names** crate to achieve this. An example of that is shown in
/// [this test](https://github.com/TedDriggs/field_names/blob/master/tests/keep_in_sync.rs).
#[derive(Builder, Default)]
#[builder(name = "MyDataBuilder", build_fn(private, name = "build_seed", error = "MyDataBuilderError"))]
struct MyDataSeed {
    /// If there are multiple ways to express a field and there's not an enum type or a conversion that
    /// could collapse it to one field in the seed, using `strip_option` will hide the internal
    /// option, making for a more useful API. The use of `default` at the field level ensures that
    /// `derive_builder` won't fail in `MyDataBuilder::build_seed` when it shouldn't.
    #[builder(default, setter(strip_option))]
    json_pre_parsed: Option<serde_json::Value>,
    #[builder(default, setter(strip_option))]
    json_string: Option<String>,
}

impl MyDataSeed {
    fn build(&self) -> Result<MyData, MyDataBuilderError> {
        // This illustrates custom validation
        if self.json_str.is_some() && self.json_pre_parsed.is_some() {
            return Err(MyDataBuilderError::Conflict("json"));
        }

        Ok(MyData {
            // This illustrates how fallback across options might be done
            json: match self.json_pre_parsed {
                Some(val) => val.clone(),
                None => match self.json_str => {
                    Some(s) => serde_json::from_str(s)?,
                    None => {
                        return Err(Error::MissingField("json")),
                    }
                }
            },
        })
    }
}

impl MyDataBuilder {
    pub fn build(&self) -> Result<MyData, MyDataBuilderError> {
        self.build_seed()?.build()
    }
}
```

**Comment by dan-da** [comment]
Ok, that's some tricky stuff.   thx for the example!

iiuc, the core idea is that MyDataSeed is a superset of MyData with the "transient" properties, the builder is derived from MyDataSeed, and a custom ::build() returns MyData instead of MyDataSeed.

It makes sense and I believe it should also work for my real use-case, though I haven't tried it yet.  (I impl'd a custom builder in the meantime).

This pattern seems quite useful, so I would urge you to add this example to the repo and highlight in the readme/docs.    It's simple enough in hindsight, but non-obvious to someone like myself new to derive_builder.

**Comment by TedDriggs** [comment]
> iiuc, the core idea is that MyDataSeed is a superset of MyData with the "transient" properties, the builder is derived from MyDataSeed, and a custom ::build() returns MyData instead of MyDataSeed.

In your case, yes - however, this pattern doesn't require that `MyDataSeed` be a strict superset (there might be a field in `MyData` that is derived from multiple fields in `MyDataSeed`, and therefore no 1:1 analogous field exists in the seed struct).

I'm not great at docs writing, so while I'd be open to reviewing a PR that added such documentation I'm unlikely to do it myself.
