### ISSUE TITLE
Option for generating both `strip_option` + non-`strip_option` versions of a setter?

### ISSUE THREAD

**Issue by helixbass** [colin-kiegel/rust-derive-builder#291]
For a struct field eg `some_field: Option<T>` where there are useful `Into<T>` implementations, it seems like the typical ideal ergonomics are to make it `setter(strip_option, into)` so that you can leverage those `Into<T>` implementations by saying `.some_field(something_that_is_into_t)`

But then as soon as you run into a case where you have an `Option` value that you want to initialize `some_field` with, my understanding is that you can either:
(a) "interrupt the chain" and say something like:
```
let mut builder = MyStructBuilder::default().some_other_field(other_value);
if let Some(some_field_value) = some_field_value {
    builder.some_field(some_field_value);
}
...
```
or (b) remove `strip_option` and then lose the ability to leverage those `Into<T>` implementations in the calls to `.some_field()`

So it strikes me as desirable ergonomics in that case to have two different setters (one of which is `strip_option` and one of which is not). Maybe using the naming convention `maybe_*()` for the non-`strip_option` one. So that I could use like:
```
// when I have an Into<T> value
MyStructBuilder::default()
    .some_field(something_that_is_into_t)
...

// when I have an Option<T>
MyStructBuilder::default()
    .maybe_some_field(option_t)
```

Is that something you would consider exposing as a declarative option?

Or if not is that something that's currently achievable via eg custom setters?

**Comment by TedDriggs** [comment]
You could definitely add your own setter to the builder in a separate `impl` block to do this. I'd personally be hesitant to allow making multiple setters off a single field; right now we sort-of adhere to the idea that you have "a setter" with some options to control its behavior, rather than "you can create a list of setters for a single field, with arbitrary combinations of options on each one."

**Comment by helixbass** [comment]
Ok ya that makes sense it does seem hard to expose in a way that wouldn't complicate the mental model

And I've had limited experience with writing custom setters but I'm understanding that they're not "magic", you just create an ordinary `impl` block (for the `derive`-generated `*Builder` struct) and can do whatever you want there, thanks
