### ISSUE TITLE
Crates.io informs that `macro-attr` supersedes `custom_derive`

### ISSUE THREAD

**Issue by nbigaouette** [colin-kiegel/rust-derive-builder#30]
Crates.io's [page for `custom_derive`](https://crates.io/crates/custom_derive) notes:

> Note: superseded by `macro-attr`

Should `rust-derive-builder` use it instead?

**Comment by nbigaouette** [comment]
The crate `custom_derive` (at version 0.1.7) was _renamed_ to `macro-attr` (at version 0.2.0).

See https://github.com/DanielKeep/rust-custom-derive/pull/24#issuecomment-261841634 and the [tracking issue for 0.2.0](https://github.com/DanielKeep/rust-custom-derive/issues/25)

**Comment by killercup** [comment]
Thanks for info!

Will close this as we are going to use macros 1.1 starting next release!
