### ISSUE TITLE
Allow way to prevent dependency on crate `alloc`.

### ISSUE THREAD

**Issue by red1bluelost** [colin-kiegel/rust-derive-builder#303]
When using the library with `no_std`, `derive_builder`'s dependency on `alloc` forces the user to provide a `global_allocator` even if they don't use anything that would require allocations (i.e. `*BuilderError::ValidationError(String)`). It would be helpful for some `no_std` libraries to have a way to disable this dependency on `alloc`.

I made a PR as a possible solution for this. It provides a feature `alloc` that controls whether `extern crate alloc` is included during no `std` feature. It also provides a `build_fn` field `validation_error` that will disable the generation of `*BuilderError::ValidationError(String)` so that is never referenced. https://github.com/colin-kiegel/rust-derive-builder/pull/302

**Comment by TedDriggs** [comment]
You should be able to avoid the usage of `String` here by providing a custom error yourself - did that still result in generated code that used `String`?

**Comment by red1bluelost** [comment]
> You should be able to avoid the usage of `String` here by providing a custom error yourself - did that still result in generated code that used `String`?

I did try custom errors and it is a good way to not import any alloc code but it does not prevent linking `alloc`. Since `extern crate alloc` still exists in 'derive_builder/src/lib.rs', it will try to link with a `global_allocator` which is mainly what I want to avoid.

**Comment by TedDriggs** [comment]
Thanks for the explanation! I am onboard with making `alloc` optional based on that, and will reexamine your PR with this in mind.

**Comment by TedDriggs** [comment]
Looks like this didn't get auto-closed by the relevant commit; the changes are in v0.13.0
