### ISSUE TITLE
Non-chaining `&mut` pattern

### ISSUE THREAD

**Issue by Kyuuhachi** [colin-kiegel/rust-derive-builder#307]
I have whole bunch of functions that look something like
 ```rs
	let mut msc = MuseScoreBuilder::default();
	xml.visit(|xml| {
		match xml.name() {
			"programVersion" => {
				msc.program_version(xml.scalar()?);
			},
			"programRevision" => {
				msc.program_revision(xml.scalar()?);
			},
			"Score" => {
				msc.score(parse_score(xml)?);
			},
			name => tracing::warn!("unknown tag {name}"),
		};
		Ok(())
	})?;
	Ok(msc.build()?)
```

This takes quite a lot more space than necessary, due to needing to discard the returned self. In most instances I can use the owned style to avoid this, but that does have its own share of ugliness. I believe adding a variant of the mutable style that does not return self would be useful in this scenario, but I don't know if it's a common enough scenario to be worth adding. Any thoughts?

EDIT: On second thought I cannot use the owned style; the borrow checker doesn't like it. Another workaround is `drop(msc.program_revision(xml.scalar()?))`, which I also do not particularly like.

**Comment by TedDriggs** [comment]
This hasn't come up before, so I'm skeptical that the need for it is widespread enough to justify an additional flag.

You could rewrite this so that there's only one bit of unnecessary code by returning `&mut msc` from the unknown tag branch:

```rust
   let mut msc = MuseScoreBuilder::default();
   xml.visit(|xml| {
   	match xml.name() {
   		"programVersion" => msc.program_version(xml.scalar()?),
   		"programRevision" => msc.program_revision(xml.scalar()?),
   		"Score" => msc.score(parse_score(xml)?),
   		name => { tracing::warn!("unknown tag {name}"); &mut msc },
   	};
   	Ok(())
   })?;
   Ok(msc.build()?)
```

**Comment by Kyuuhachi** [comment]
Yeah, that's fair. Returning the builder and `drop()` are both perfectly fine workarounds, so yeah probably not worth the added complexity.

**Comment by Kyuuhachi** [comment]
Someone pointed out a third option, `"Score" => _ = msc.score(parse_score(xml)?),`, which also works nicely.
