### ISSUE TITLE
Forward the method to an internal struct?

### ISSUE THREAD

**Issue by nbigaouette** [colin-kiegel/rust-derive-builder#31]
I'd like to add builders to my struct, but the fields are "hidden" in an internal struct. For example, my structs look like this:
```
struct InternalStruct {
    a: bool,
    b: i64,
    // etc.
}
pub struct MyStruct {
    a: A,
    internal: InternalStruct,
}
```

It would be great to be able to add `Builder` to `MyStruct` and tell it to:
1. "forward" the setters to the internal struc;
2. Possibly _ignore_ `a` (don't create a setter for it).

I use this to move `InternalStruct` in a `serde_types.in.rs` file to be `Serialize`d/`Deserialize`d. In my case above the type `A` _cannot_ be serialized so I need to split the two structs. Also, I don't want `a` to have a setter since it's passed as `MyStruct`'s constructor (hence 2.)

Also, I think this might be useful to encapsulate common members of multiple structs into a single one "a la" inheritance.

**Comment by colin-kiegel** [comment]
I guess this is something for `macros 2.0`, i.e. fully featured procedural macros.

The main problem I see here is that we need read access to both structs simultaneously. This is not possible with macros 1.1 - at least not with some fragile hacks involving a global state.

But we can already discuss it of course. I can imagine different alternative apis / annotations
- `forward`
- `flatten`
- `expand`
- ...

I lean towards something like `flatten` or `expand` right now.

The question is, if that (implicitly) replaces the setter for `internal` or if the user can keep that setter too and choose whether to set internal or its nested fields. If the user set both, we could either error or apply the _more specific_ nested field values to the given value of `internal`.

**Comment by TedDriggs** [comment]
This could be handled by the manual setter discussed in #110, but there are a lot of questions around maintaining interim state if the value is forwarded to a method of an internal struct. I don't see `derive_builder` being the first mover in this space, and we'll probably copy `serde` if they ever do this.
