### ISSUE TITLE
Support arbitrary expression for `#[builder(default = ...)]`

### ISSUE THREAD

**Issue by bew** [colin-kiegel/rust-derive-builder#330]
Hello!

I initially tried out the [`typed-builder`](https://github.com/idanarye/rust-typed-builder) crate but realized I needed runtime checks.
While migrating to `derive_builder` I noticed the syntax for default is less ergonomic.

With `typed-builder` I could do: `#[builder(default = "foo".into())]`
But with `derive_builder` I need to wrap the fn in a string:  `#[builder(default = r#""foo".into()"#)]` which is much less ergonomic, and in an editor I can't do actions like 'go-to-definition'.

So here I am, asking to support that ;)

**Comment by TedDriggs** [comment]
I've put up a PR for this, though I haven't had enough time to fully test it, and I was seeing some weird behavior from rust-analyzer in vscode after I made the change.

**Comment by bew** [comment]
Hello again, thanks a lot for the impl it looks like great and simple! 

Do you have any plans to make a release some time 'soon'(-ish) ?
