### ISSUE TITLE
missing_docs

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#37]
The following fails
```
#![deny(missing_docs)]
#[derive(Builder)]
struct Foo {
    bar: bool
}
```
with `error: missing documentation for a method`.

While doing this we should probably add some other `deny`s to our tests, to be sure.

**Comment by killercup** [comment]
Diesel uses

    #![deny(warnings, missing_debug_implementations, missing_copy_implementations)]

fyi

**Comment by colin-kiegel** [comment]
Thx - is it possible to set that specifically for `cargo test` but not `cargo build` (when applied to the crate itself)?

Use case: Rust might introduce deprecation warnings, but we still want the _build_ to succeed.

**Comment by killercup** [comment]
You mean like `#[cfg_attr(test, allow(missing_docs))]`?

**Comment by colin-kiegel** [comment]
perfect, thanks! :-)
