### ISSUE TITLE
Use full path for Result

### ISSUE THREAD

**Issue by 0g00** [colin-kiegel/rust-derive-builder#39]
I think you should use `std::result::Result` instead `Result` in [this place](https://github.com/colin-kiegel/rust-derive-builder/blob/master/src/lib.rs#L357).
Cause: if declare or `use` custom type `Result` it will throw error: `error[E0244]: wrong number of type arguments: expected 1, found 2`

**Comment by killercup** [comment]
True! (With a leading `::` to make this _really_ begin at the root level)

Want to make a quick PR with the change and a test that has something like `type Result = ();` at the top?

**Comment by colin-kiegel** [comment]
Thank you, I guess the same is true for all other standard types like `Option`
https://github.com/colin-kiegel/rust-derive-builder/blob/master/src/lib.rs#L387
