### ISSUE TITLE
Is it possible to add generic setters?

### ISSUE THREAD

**Issue by ayoshi** [colin-kiegel/rust-derive-builder#42]
Ideally I would want some setters to recieve, for example somthing like ```Option<Into<Type>>```, even just ```Into<Type>```. For example ```ToSocketAddrs```. Or functions.

**Comment by killercup** [comment]
I think all our setters are already accepting `Into<T>` if your type is `T`.

**Comment by colin-kiegel** [comment]
@killercup yes, it's `Into<T>`. But, what if we would change the signature
to `Into<Option<T>>`? This would allow elegant unsetting via `foo(None)`
and still accept `foo(x)` where `x: Into<T>`, wouldn't it? Is there a
generic `impl Into<Option<T>> for U where U: Into<T>`? :-)

Pascal Hertleif <notifications@github.com> schrieb am Do., 16. Feb. 2017,
19:50:

**Comment by killercup** [comment]
`Into<Option<_>>` exists and allows you to do stuff like `.foo("bar")` as well as `.foo(None)` (it converts non-None to the Some case). I think you'll actually need `Into<Option<Into<T>>>` here, though. And this has implications for type inference, as you'd have to call `into()` twice, once for the Option, and once for the inner value. (I talked about a similar case with florob at the last meetup.)

**Comment by ayoshi** [comment]
For example, I can't express getter like this one, can't I?

```
struct Config {
    app_server: SocketAddr;
}
...
fn app_server<A: ToSocketAddrs>(addr: A) -> SocketAddr {
}
...
```

I don't want the user passing SocketAddr directly, he only needs to pass a String. Right now, what I have to do is declare the parameter as ```String```, and convert it in the custom builder method.

If I could wrap it into Option - even better.

**Comment by ayoshi** [comment]
And by the way, this will also not work:

```
#[derive(PartialEq, Clone, Builder)]
struct Config {
    hostname: Option<String>;
}
...
ConfigBuilder::new().hostname("localhost").build();
``

```
error[E0277]: the trait bound `std::option::Option<std::string::String>: std::convert::From<&str>` is not satisfied
```

**Comment by colin-kiegel** [comment]
@ayoshi
- Regarding your first post: What's the relation of `ToSocketAddrs` and `SocketAddr`, if `ToSocketAddrs = Into<SocketAddr>` then this is exactly what derive builder does
- in the second example you need to either change the field to `hostname: String` or change the setter call to `hostname("localhost".to_string())`

**Comment by ayoshi** [comment]
@colin-kiegel ToSocketAddrs it's a way to convert any compatible object into SocketAddr. https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html

**Comment by colin-kiegel** [comment]
Ok, I assumed it was a custom type - sorry. ;-)

No, that's not possible, because derive builder currently wouldn't know that it needs to call `::std::net::ToSocketAddrs::to_socket_addrs(x)` to convert from `x: ToSocketAddrs` to `SocketAddrs`.

If we want to support something like this we would need to invent some kind of annotation to tell derive builder to do so.

You could implement a new type `struct MySocket(SocketAddrs)` and `impl From<T: ToSocketAddrs> for MySocket` I guess. That way derive Builder would understand that it can call `.into()` on  anything `ToSocketAddrs`.

**Comment by ayoshi** [comment]
@colin-kiegel  Wow, that's a great idea, thank you.

Still, it would be very nice that all those `Into` conversions would also work with Option<T>.
There are many, many cases like this, most of the types that convert from &str or String, for example ```PathBuf```

Ideally user could pass any compatible object, either a string or a PathBuf directly, if he has it already (for example he received it from some function) but still use `Option<PathBuf>`, and set default (when the default will be implemented :)  )to `None`, this way I could match on whether setting was passed or not. The only way to work around that right now, is receive an object and set default to some dummy value, which would mean that I need match on a value, instead of a type to perform the correct action (not the Rust way, I suppose).

**Comment by colin-kiegel** [comment]
@killercup I thought std could implement something [like this](https://play.rust-lang.org/?gist=4566e2660525b579f5112746c159a557&version=stable&backtrace=0) for `Option`, but it can't :cry: ... I'd hoped that Rust would understand `impl<T> From<T> for T` as more specialized than `impl<T, U> From<T> for MayBe<U> where T: Into<U>` since it has one parameter less. But I am not very familiar with specialization rules. _MayBe_ they could be improved??

```rust
enum MayBe<T> { // <-- corresponds to Option
    Yup(T),
    Nope,
}

use MayBe::{Yup, Nope};

// T -> U && U -> MayBe<U>  =>  T -> MayBe<U>
impl<T, U> From<T> for MayBe<U> where T: Into<U> {
    fn from(x: T) -> Self {
        Yup(x.into())
    }
}

// error[E0119]: conflicting implementations of trait
//      `std::convert::From<MayBe<_>>` for type `MayBe<_>`
// 
// i.e. for `T = MayBe<U>`
// and if we assume some crazy `U where MayBe<U>: Into<U>` (you never know)
// 
// This conflicts with
// - `impl<T> From<T> for T`
```

**Comment by colin-kiegel** [comment]
@ayoshi https://users.rust-lang.org/t/impl-t-u-from-option-t-for-option-u-where-t-into-u/9508

**Comment by TedDriggs** [comment]
I can think of two near-term solutions to this; I'd be curious to get everyone's feedback on the approaches.

Right now, there's no way to skip generating a setter without turning the backing field into `PhantomData`. We could amend that in one of two ways:

1. Add `#[builder(setter(manual))]`. This would generate the field but not the setter, allowing the user to write their own. This has the downside of making the author keep the field and setter names in sync by hand :(
1. Add `#[builder(setter(bound="T: ToSocketAddr", with="path::to::adapter"))]`. The `with` clause is a path to a function that takes `Fn(T) -> ???` (either the field type, something that converts to the field type, or an Option of the field type?)

I'm not a huge fan of either approach; I have a strong dislike for manually keeping names in sync, but I think approach 2 may be a step too far in the metaprogramming direction. Though FWIW, serde  basically does approach 2 and it seems to work pretty well for them.

**Comment by TedDriggs** [comment]
Turns out this relates to #110; it's another case for the manual setter.

**Comment by TedDriggs** [comment]
Per previous comment, this seems better tracked through #110.
