### ISSUE TITLE
Change default build_fn name from `build` to `try_into` in preparation for `TryFrom`/`TryInto` traits?

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#54]
[`TryFrom<T>` and `TryInto<T>`](https://github.com/rust-lang/rfcs/blob/master/text/1542-try-from.md) are about to be stabilized. These would be the idiomatic builder traits IMO. And they are likely to end up in the std prelude, so you _wouldn't_ need to import them.

The current build method, could be replaced by `TryFrom` (which implies `TryInto`)
```rust
impl TryFrom<FooBuilder>: Foo {
    type Err = String;

    fn try_from(b: FooBuilder) -> Result<Foo, String> {
         // ...
    }
}
```

_Removing_ `FooBuilder::build()` in favour of `TryFrom::try_from()` would be a breaking change. 

However we could keep the current default fn `build()` until `TryFrom` is stabilised. Then let `build` wrap around `TryFrom` and keep it this way virtually forever (unless opted out).

Alternatively, we could try to get rid of the wrapping `build()` fn as early as possible. This could happen in two steps (a) rename `build()` to `try_into()` and (b) switch to `TryFrom`, while `builder.try_into()` should still magically work  in almost all cases.  There could still be an option to opt into creating such a wrapper function with a custom name.

`derive_builder` is still young, so we may deprecate things more easily now rather than later. The question is, where do we want to end up long term? Do we want to keep a `build()` fn wrapper as default behaviour, or do we want to advocate using `TryFrom` and not have a wrapper by default?

**Comment by TedDriggs** [comment]
The `try_into` method would be both inherent and trait-defined, right? Having to add another `use` statement would be unfortunate. Also, I vaguely recall something about offering descriptive inherent method names, but I can't find it on Google and it may have been specific to types in `std`.

**Comment by colin-kiegel** [comment]
It depends. If `use TryFrom; use TryInto` were encluded in the std prelude, I could imagine only offering these trait implementations by default. An inherent / type method could then be generated by demand.

If these traits don't end up in the std prelude, then an inherent method is definitely needed.

Speaking of std: Generally I would like to mimic design philosophies of `std` as close as possible, to make this crate intuitive. So if you think that something violates a design principle of std that would be a strong argument for me to reconsider these choices. :-)

Would you suggest to always keep an inherent `build()` method by default, because it is more descriptive? One upside of that is, that we could avoid a breaking change, unless we want to rename it `try_build()` depending on signature. :-)

**Comment by TedDriggs** [comment]
I asked @steveklabnik about the "descriptive inherent method names" and his response was "i don't know what you're talking about", so I think I'm remembering it wrong.

After thinking about this more, I'd suggest implementing both `From` and `TryFrom`, and deprecating the `build` method (but not removing it outright just yet).

1. If the programmer fully controls the builder's inputs, then an error in construction should panic - same as an out-of-bounds index access. In this case, they can call `into()` which is idiomatic and easy to read.
1. If the programmer _doesn't_ control the builder's inputs, then they can use `try_into()` and then match on the result.

**Comment by sfackler** [comment]
I would personally advocate for keeping a `build` method in addition to `Into`/`TryInto` impls.

IMO,
```rust
let foo = FooBuilder::new()
    .set_bar(10)
    .set_baz(true)
    .build();
```
is more clear in intent than
```rust
let foo = FooBuilder::new()
    .set_bar(10)
    .set_baz(true)
    .into();
```

In particular, we actually want to discourage the use of `.into` in contexts where you're not working with a generic `T: Into<U>`: https://github.com/rust-lang/rust/issues/36443

**Comment by colin-kiegel** [comment]
:+1: Thank you both for your input to this discussion. :-)

My tendency would now be to stick with the `build` method and implement `Into`/`TryInto` _additionally_, where `Into` will only be implemented if it cannot fail (i.e. all fields have defaults). It is actually a requirement of Into that it must not fail ([see definition](https://doc.rust-lang.org/core/convert/trait.Into.html)).
