### ISSUE TITLE
Infallible Build method

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#56]
The build method currently fails, if a field value was not initialized and no default value was provided (possible since custom defaults #3 are implemented).

# Proposal

Add a way to change the signature of the `build` method from `Result<Foo, _>` to `Foo`. This method would _not_ panic. Instead `derive_builder` would deny that change of signature if the method is fallible.

# Questions

How should this annotation be called? Here are two suggestions:
- `#[builder(infallible)]`
- `#[builder(no_result)]`
- `#[builder(deny_failure)]`

Should this be scoped with other build-method-related options, e.g. inside - `#[builder(buildfn(...))]`?

# Outlook

It is likely that `derive_builder` will have other failure modes in the future, such as field-specific custom validations (`foo` must be in `0..10`, etc.). These features can not be activated if the infallible build method is also active.

# Alternatives

- Change the signature of the `build` method automatically when it cannot fail. This may be surprising if you have a lot of code depending on the current signature, then you add a default value to a field (which seems like a non-breaking change) and then nothing compiles anymore. Not good.
- Always allow changing the signature to `Foo` even if the `build` method is fallible. Panic on failure. This does not seem to be idiomatic Rust - which we try to achieve as best as possible. If someone really wants that behaviour he/she can implement a custom wrapper (we will add means to rename the build method and make it private).

**Comment by colin-kiegel** [comment]
Anyone reading this - I am looking for feedback on the naming question. This should be reasonably understandable to anyone reading it for the first time, without prior knowledge of `derive_builder`.

A general question is, whether this option should be scoped with other settings that refer to the `build()` method, like skipping, renaming, visibility-level (public/private). I will add this question, but it seems like scoping would be a good idea.

**Comment by TedDriggs** [comment]
> Always allow changing the signature to Foo even if the build method is fallible. Panic on failure. This does not seem to be idiomatic Rust - which we try to achieve as best as possible. If someone really wants that behaviour he/she can implement a custom wrapper (we will add means to rename the build method and make it private).

I'd argue that this _is_ idiomatic; Rust often provides methods which panic on failure, and leaves it up to the programmer to decide whether to use those methods or to use the ones that return `Option` or `Result`. A great example is the `Index` trait vs. the `get` method; the former panics while the latter returns an option.

@joeduffy wrote about this (at some length) on his blog [here](jdb); the relevant quote is "bugs aren't recoverable errors". If I'm using the builder for programmer convenience rather than to integrate user input, then my program has no chance of gracefully handling a failure - I'll write `build().unwrap()` and the program will _still_ panic if I made a mistake, but now there's an extra method call there.

[jdb]: http://joeduffyblog.com/2016/02/07/the-error-model/#bugs-arent-recoverable-errors

**Comment by colin-kiegel** [comment]
@TedDriggs Ok, you're right - what's idiomatic may in fact depend on how you use the builder and what you want to achieve. :-)

My _primary_ target is the use case where a crate A uses derive_builder to create some public API. In that case crate A cannot reason about how crate B will use that public API (especially whether user input will be involved, or not). In case of doubt, returning a `Result` seems like a good default, because it is quite easy to call `unwrap()`. However it is not that easy to [catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) a panicking method - and also not recommended.

I could imagine to have three modes

1. return `Result<Foo, _>` -> current behaviour (and supposedly future default)
2. return `Foo` _never_ panic -> this would give additional _guarantees_ at the cost of some features. Especially in the case of crate A creating a public API this might be very desirable.
3. return `Foo` _may_ panic -> convenience for cases where you use the builder internally (i.e. not for a public API) and just want to `unwrap` everything.

I believe the general priority of these modes for derive_builder should be 1 > 2 > 3. And probably the order in which I'd implement it.

But I'm also not fully convinced that it would add much value to have this third mode of panicking build methods. This is certainly a matter of personal style and preferences, but when I read someone elses code I would prefer to read some explicit `build().unwrap()` instead of implicitly panicking `build()`. Because the problem of implicitly panicking is, that you might not expect it from a build method - especially if it's an opt-in mode, which may be different for each builder. I think good code should always focus more on what's easy to read(*) over what's easy to write. That's why I don't really want to _encourage_ panicking build methods.

(*) If _all_ build methods would _always_ be panicking, then it would be different thing.

A solution might be to have a panicking variant default to a different name, let's call it `construct()` for the moment. But then there is also the trade-off with managing feature creep and keeping the documentation of derive_builder in a manageable scope.

I'm not fully closed to panicking `build`-like methods, but I'd give it a rather low priority right now for the above reasons.

**Comment by TedDriggs** [comment]
> My primary target is the use case where a crate A uses derive_builder to create some public API. In that case crate A cannot reason about how crate B will use that public API (especially whether user input will be involved, or not).

If every builder exposed both methods, wouldn't crate B be the one deciding whether to go the result route or the panic route? I've been working under the assumption that crate A would never take a builder as input - it would always take the constructed object.

I'd be interested in trying to make a PR with the behavior I'm suggesting, but I don't want to run counter to your goals for the API design.

An alternative approach might be to expose a `Builder<T>` trait on the generated structs; I could then make a `ForceBuilder<T>` trait and provide a blanket impl in my own crate.

**Comment by colin-kiegel** [comment]
Hm, that trait based approach sounds interesting. :-)

However there are currently some limitations. A proc_macro crate like derive_builder cannot export any items like traits. This raises the question where else  to define a trait like `Builder<T>`. Luckily there are the `TryFrom` and `From` traits in std (which imply `TryInto`/`Into`). However `TryFrom` is still unstable and an extension trait `ForcedTryInto` might catch more than you want.

I could imagine to introduce the `TryFrom` implementation behind a feature flag. Would that help you, or are you developing on the stable toolchain?

**Comment by faern** [comment]
According to https://aturon.github.io/ownership/builders.html the constructor of the builder should take all the required fields. It would be easy to create infallible builders if all required (no defaults exist) fields were changed from `Option<Foo>` into `Foo` in the builder struct and they were taken in the constructor. All those fields must be given anyway, so why not get that over with in the constructor of the builder?

I find myself using builders for structs with 1-2 fields that does not have defaults and then a myriad of fields that have defaults. In those cases the above would be much more ergonomic:
```rust
let foo = FooBuilder::new(a, b).c(c).build();
// VS
let foo = FooBuilder::new().a(a).b(b).c(c).build().unwrap();
```

There can still be setters for the required fields, since one might want to keep the same builder, change the values and create more `Foo`s.

So when activating infallible builder we can implement it in such a way that one can choose between two modes:
1. `#[builder(infallible(constructor))]`: All fields that must be set are being arguments to the constructor and are not stored inside `Option`s in the builder struct. No panics possible. But changing the constructor name from `default` to `new` might make it look better?
2. `#[builder(infallible(panic))]`: The required fields are kept as `Option<Foo>` in the builder, but `build()` will panic if they are not set.

**Comment by colin-kiegel** [comment]
Interesting proposal. Hm, I can see the advantage of knowing statically that this will not panic.

However I also see some disadvantages
- the more verbose form `default().foo(a).bar(b).baz(c).build()` may be easier to read, because you can immediately see that the value `a` is used as `foo`.
- it is also more flexible. What if the calls to builder happen dynamically (user input / etc.) and you _don't know_ whether all required fields will be present.

Therefore it should be opt-into behaviour to let the user choose which solution fits best.

**Comment by faern** [comment]
The readability may vary depending on types and values. In my current use case I do firewall rules, and it becomes pretty apparent what is what even in the constructor:
```rust
let rule = FilterRuleBuilder::new(RuleAction::Pass).from(my_ip).build();
```

If you are in a situation where you don't know all the values up front and don't even know if they will be present I would argue you are not in an infallible situation and you don't want an infallible builder to begin with. This infallible stuff should be opt-in I agree, so would not affect use cases with user input etc.

**Comment by colin-kiegel** [comment]
I guess the infallible build method will be _mutually exclusive_ with a custom validate function #67.

**Comment by faern** [comment]
Yes, that sounds reasonable.

I'm imagining it like this: If you look at your proposed error enum in the structured errors issue: https://github.com/colin-kiegel/rust-derive-builder/issues/60#issuecomment-289284925. I would say that infallible builds should be possible to activate when all those variants are absent. If we make the enums only appear when relevant, `CustomDefault` would only be a variant when a custom default is specified for a field etc. Then the statically infallible builds would only be possible when the error enum is empty. But it would of course also make it possible to force infallible builds with panics even in the builders that have possible errors.

**Comment by tkaitchuck** [comment]
It should be possible to make the build infallible even with default parameters. See the end of: 
https://dev.to/mindflavor/rust-builder-pattern-with-types-3chf
That obviously doesn't help if there is custom validation logic. (But the user is already specifying a flag in that case anyway, so having different behavior is expected.)

**Comment by TedDriggs** [comment]
After almost five yeas, this issue is no closer to implementation so I'm going to close it out.

For those who want to present an infallible build method while using `derive_builder`, the recommended approach would be:

1. Use `#[builder(build_fn(private, name = "fallible_build"))]` to hide and rename the provided build method.
2. Add an explicit `impl` block like the following:

```rust
impl FooBuilder {
    pub fn new(required: String, other: String) -> Self {
        // ...
    }

    pub fn build(&mut self) -> Self {
        self.fallible_build().expect("All required fields set at initialization")
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn no_required_fields_added_to_foo() {
        // This will panic if any fields have been added to Foo (and therefore FooBuilder)
        // that lack defaults.
        FooBuilder::new("first".into(), "second".into()).build()
    }
}
```

The provided unit test catches cases of code drift; if `Foo` gets a new required field, the test will fail, with the panic specifying exactly which field is missing.

Note: There isn't currently a way to make a builder _not_ `impl Default`. #136 discussed this before, and while that issue is closed, I'd be receptive of a new issue that proposed a narrower opt-out for this specific use-case. I'm not sure if/where the generated code currently relies on the builder implementing `Default`, so this may be more involved than it sounds.

**Comment by Sajjon** [comment]
@TedDriggs @colin-kiegel I have an idea for a builder where you need not call `unwrap` (or even `build`):

I present a solution below I think is quite nice, it has these advantages:
- No need to call `unwrap`
- Actually no need to call `build()` even! But in my example below I chose to include that... but can be dropped
- Sets a canonical order of fields, which is good in a shared code base

The implementation below can probably be performance optimized. One can imagine support for panicing validation 

What do you think?

```rust
#![allow(non_camel_case_types)]

#[derive(Debug, PartialEq)]
pub struct Person {
    // ~~~ Non-optional-non-default fields MUST go FIRST ~~~
    pub year_born: u16,

    // ~~~ Non-optional-default fields MUST go SECOND ~~~
    // #[builder(default = true)]
    pub is_alive: bool,
    // #[builder(default = false)]
    pub has_visited_europe: bool,

    // ~~~ Optional fields MUST go THIRD ~~~
    pub dog_name: Option<String>,
    pub spouse_name: Option<String>,
}

impl Person {
    // or "builder_ordered"
    pub fn builder() -> __PersonBuilderNoFieldsSet {
        __PersonBuilderNoFieldsSet::default()
    }
}

// ~~~ ALL fields set ~~~
pub struct __PersonBuilderFieldsSet_0_1_2_3_4 {
    pub year_born: u16,
    pub is_alive: bool,
    pub has_visited_europe: bool,
    pub dog_name: Option<String>,
    pub spouse_name: Option<String>,
}
impl __PersonBuilderFieldsSet_0_1_2_3_4 {
    pub fn build(self) -> Person {
        Person {
            year_born: self.year_born,
            is_alive: self.is_alive,
            has_visited_europe: self.has_visited_europe,
            dog_name: self.dog_name,
            spouse_name: self.spouse_name,
        }
    }
}

// ~~~ Fields set: 0, 1, 2, 3 ~~~
#[derive(Default)]
pub struct __PersonBuilderFieldsSet_0_1_2_3 {
    year_born: u16,
    is_alive: bool,
    has_visited_europe: bool,
    dog_name: Option<String>,
}
impl __PersonBuilderFieldsSet_0_1_2_3 {
    pub fn spouse_name(
        self,
        value: impl Into<Option<String>>,
    ) -> __PersonBuilderFieldsSet_0_1_2_3_4 {
        __PersonBuilderFieldsSet_0_1_2_3_4 {
            year_born: self.year_born,
            is_alive: self.is_alive,
            has_visited_europe: self.has_visited_europe,
            dog_name: self.dog_name,
            spouse_name: value.into(),
        }
    }

    pub fn build(self) -> Person {
        // can forward to last builder
        self.spouse_name(None).build()
    }
}

// ~~~ Fields set: 0, 1, 2 ~~~
#[derive(Default)]
pub struct __PersonBuilderFieldsSet_0_1_2 {
    year_born: u16,
    is_alive: bool,
    has_visited_europe: bool,
}
impl __PersonBuilderFieldsSet_0_1_2 {
    pub fn dog_name(self, value: impl Into<Option<String>>) -> __PersonBuilderFieldsSet_0_1_2_3 {
        __PersonBuilderFieldsSet_0_1_2_3 {
            year_born: self.year_born,
            is_alive: self.is_alive,
            has_visited_europe: self.has_visited_europe,
            dog_name: value.into(),
        }
    }

    pub fn spouse_name(
        self,
        value: impl Into<Option<String>>,
    ) -> __PersonBuilderFieldsSet_0_1_2_3_4 {
        // can forward to next builder
        self.dog_name(None).spouse_name(value)
    }

    pub fn build(self) -> Person {
        // can forward to next builder
        self.spouse_name(None).build()
    }
}

// ~~~ Fields set: 0, 1 ~~~
#[derive(Default)]
pub struct __PersonBuilderFieldsSet_0_1 {
    year_born: u16,
    is_alive: bool,
}

impl __PersonBuilderFieldsSet_0_1 {
    // N.B. calling this will use the Default value of `is_alive
    pub fn has_visited_europe(self, value: impl Into<bool>) -> __PersonBuilderFieldsSet_0_1_2 {
        __PersonBuilderFieldsSet_0_1_2 {
            year_born: self.year_born,
            is_alive: self.is_alive,
            has_visited_europe: value.into(),
        }
    }

    pub fn dog_name(self, value: impl Into<Option<String>>) -> __PersonBuilderFieldsSet_0_1_2_3 {
        // value is read using `#[builder(default = ...)]` but I dont have access to that in this minimal crate
        let default_for_has_visited_europe = Person::default_for_has_visited_europe();
        // can forward to next builder
        self.has_visited_europe(default_for_has_visited_europe)
            .dog_name(value)
    }

    pub fn spouse_name(
        self,
        value: impl Into<Option<String>>,
    ) -> __PersonBuilderFieldsSet_0_1_2_3_4 {
        // can forward to next builder
        self.dog_name(None).spouse_name(value)
    }

    pub fn build(self) -> Person {
        // can forward to last builder
        self.spouse_name(None).build()
    }
}

// ~~~ Fields set: 0 ~~~
#[derive(Default)]
pub struct __PersonBuilderFieldsSet_0 {
    year_born: u16,
}

impl __PersonBuilderFieldsSet_0 {
    pub fn is_alive(self, value: impl Into<bool>) -> __PersonBuilderFieldsSet_0_1 {
        __PersonBuilderFieldsSet_0_1 {
            year_born: self.year_born,
            is_alive: value.into(),
        }
    }

    // N.B. calling this will use the Default value of `is_alive
    pub fn has_visited_europe(self, value: impl Into<bool>) -> __PersonBuilderFieldsSet_0_1_2 {
        // value is read using `#[builder(default = ...)]` but I dont have access to that in this minimal crate
        let default_is_alive = Person::default_for_is_alive();
        // can forward to next builder
        self.is_alive(default_is_alive).has_visited_europe(value)
    }

    pub fn dog_name(self, value: impl Into<Option<String>>) -> __PersonBuilderFieldsSet_0_1_2_3 {
        // value is read using `#[builder(default = ...)]` but I dont have access to that in this minimal crate
        let default_for_has_visited_europe = Person::default_for_has_visited_europe();
        // can forward to next builder
        self.has_visited_europe(default_for_has_visited_europe)
            .dog_name(value)
    }

    pub fn spouse_name(
        self,
        value: impl Into<Option<String>>,
    ) -> __PersonBuilderFieldsSet_0_1_2_3_4 {
        // can forward to next builder
        self.dog_name(None).spouse_name(value)
    }

    pub fn build(self) -> Person {
        // can forward to last builder
        self.spouse_name(None).build()
    }
}

// ~~~ No fields set ~~~
#[derive(Default)]
pub struct __PersonBuilderNoFieldsSet;
impl __PersonBuilderNoFieldsSet {
    pub fn year_born(self, value: impl Into<u16>) -> __PersonBuilderFieldsSet_0 {
        __PersonBuilderFieldsSet_0 {
            year_born: value.into(),
        }
    }
}

// I dont have access to `#[builder(default = ...)]` in this minimal crate
// so I have to define these methods manually
#[cfg(debug_assertions)]
impl Person {
    // This is set using `#[builder(default = true)]` but I
    // dont have access to that in this minimal crate
    fn default_for_is_alive() -> bool {
        true
    }
    // This is set using `#[builder(default = false)]` but I
    // dont have access to that in this minimal crate
    fn default_for_has_visited_europe() -> bool {
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn setting_all() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .has_visited_europe(true)
            .dog_name("Rex".to_owned())
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: true,
                dog_name: Some("Rex".to_owned()),
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }

    #[test]
    fn all_but_is_alive() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .has_visited_europe(true)
            .dog_name("Rex".to_owned())
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: true,
                dog_name: Some("Rex".to_owned()),
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }

    #[test]
    fn all_but_has_visited_europe() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .dog_name("Rex".to_owned())
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: Some("Rex".to_owned()),
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }

    #[test]
    fn all_but_dog_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .has_visited_europe(true)
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: true,
                dog_name: None,
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }

    #[test]
    fn all_but_spouse_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .has_visited_europe(true)
            .dog_name("Rex".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: true,
                dog_name: Some("Rex".to_owned()),
                spouse_name: None,
            }
        )
    }

    #[test]
    fn setting_only_required() {
        let sut = Person::builder().year_born(1990_u16).build();

        assert_eq!(
            sut,
            Person {
                year_born: 1990,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: None,
                spouse_name: None,
            }
        )
    }

    #[test]
    fn setting_required_and_only_is_alive() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: None,
                spouse_name: None,
            }
        )
    }

    #[test]
    fn setting_required_and_only_has_visited_europe() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .has_visited_europe(true)
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: true,
                dog_name: None,
                spouse_name: None,
            }
        )
    }

    #[test]
    fn setting_required_and_only_dog_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .dog_name("Rex".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: Some("Rex".to_owned()),
                spouse_name: None,
            }
        )
    }

    #[test]
    fn setting_required_and_only_spouse_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: None,
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }

    #[test]
    fn setting_required_and_defaults_only() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .has_visited_europe(true)
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: true,
                dog_name: None,
                spouse_name: None,
            }
        )
    }

    #[test]
    fn setting_required_and_optionals_only() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .dog_name("Rex".to_owned())
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: Some("Rex".to_owned()),
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }

    #[test]
    fn setting_required_and_is_alive_and_dog_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .dog_name("Rex".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: Some("Rex".to_owned()),
                spouse_name: None
            }
        )
    }

    #[test]
    fn setting_required_and_is_alive_and_spouse_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .is_alive(false)
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: false,
                has_visited_europe: Person::default_for_has_visited_europe(),
                dog_name: None,
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }

    #[test]
    fn setting_required_and_has_visited_europe_and_dog_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .has_visited_europe(true)
            .dog_name("Rex".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: true,
                dog_name: Some("Rex".to_owned()),
                spouse_name: None,
            }
        )
    }

    #[test]
    fn setting_required_and_has_visited_europe_and_spouse_name() {
        let sut = Person::builder()
            .year_born(1987_u16)
            .has_visited_europe(true)
            .spouse_name("Taylor".to_owned())
            .build();

        assert_eq!(
            sut,
            Person {
                year_born: 1987,
                is_alive: Person::default_for_is_alive(),
                has_visited_europe: true,
                dog_name: None,
                spouse_name: Some("Taylor".to_owned()),
            }
        )
    }
}

```

**Comment by mathstuf** [comment]
While that certainly is nice…I really worry about compile times.

**Comment by TedDriggs** [comment]
@Sajjon that's a cool concept, and one that others have successfully used to create builder crates.

That said, it's not a good fit for this crate.

There are tradeoffs to that approach:

1. @mathstuf points out that compile times are a concern, as is the amount of code generated.
2. Imposing a requirement on the field order may be a problem for structs that have their order constrained by other macros.
3. It is very painful to pass those builders across function boundaries, since you need to name their type.

Given these tradeoffs, we've decided to allow other crates to explore those kinds of solutions while keeping `derive_builder` focused on the approach originally chosen years ago, since it seems to fill a useful niche for our users.

**Comment by Sajjon** [comment]
Indeed, compile times would blow up. Having `N+1` many builder structs for `N` many fields is not reasonable. It might be useful in small code bases, but as you say, outside the scope of Derive Builder.

Thanks!
