### ISSUE TITLE
nightly build fails on travis

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#6]
https://travis-ci.org/colin-kiegel/rust-derive-builder/jobs/150325687

The reason is https://github.com/huonw/travis-cargo/issues/23#issuecomment-143977112

shall we add the unstable feature in `Cargo.toml` or set `TRAVIS_CARGO_NIGHTLY_FEATURE=""` in `.travis.yml`?

**Comment by killercup** [comment]
I'd set `TRAVIS_CARGO_NIGHTLY_FEATURE=""` for now.
