### ISSUE TITLE
Field-level #[builder(default = __)] easier to use wrong than right

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#65]
```rust
#[derive(Debug, PartialEq, Builder)]
struct Dolor {
    msg: String,
    
    #[builder(default = "self.msg")]
    z_failure: Option<String>
}
```

This produces the following error:

```
error[E0507]: cannot move out of borrowed content
    |
169 |     #[derive(Debug, PartialEq, Builder)]
    |                                ^^^^^^^ cannot move out of borrowed content
```

Alternatively, some really weird things can be accomplished:

```rust
#[derive(Debug, PartialEq, Builder)]
struct Dolor {
    
    #[builder(default)]
    msg: String,

    /// Prints 'hi' if not explicitly initialized.
    #[builder(default = "{println!(\"Hi!\"); Some(\"woot\".to_string())}")]
    z_failure: Option<String>
}
```

The only time the current implementation of this will work at the field level is if the user provides a literal or a value that implements `Copy`. Serde avoids this by requiring the value of `default` to be a function with the signature `Fn() -> T`, which it calls every time it needs a new instance. That feels much more hygienic than the current behavior (and makes using `default` in conjunction with helper or factory functions much cleaner).

@colin-kiegel, how would you feel about combining this with #61 and documenting the breaking change as "aligned `default` behavior with serde"?

**Comment by colin-kiegel** [comment]
Hm, thanks. 

There was a discussion about this [here (comparison with serde / question 1)](https://github.com/colin-kiegel/rust-derive-builder/pull/53#pullrequestreview-28219549) and [in this comment below](https://github.com/colin-kiegel/rust-derive-builder/pull/53#pullrequestreview-28219549):

> I feel like the semantics of `#[serde(default = "some::Function::foo")]` would be too restrictive for derive_builder.
>
> * I suspect a lot of _simple_ cases where delegation to `some::Function::foo` would be overkill and `default="42"` is really all you want
> * For _complex_ cases it would seem beneficial to delegate to _methods_ on `FooBuilder` which can inspect all builder fields.
>
> It would have been nice to share the semantics with a popular crate like serde. But this would have significant drawbacks IMO.

The outcome of that discussion was, _please delegate to methods if that makes sense (complex stuff), or use arbitrary expressions if you know what you are doing (only really recommended for simple const expressions)_. The docs [clearly recommends](https://docs.rs/derive_builder/0.4.0/derive_builder/#tips) delegating to helper methods.

I still believe that 100% serde-behaviour is not a good fit for derive_builder. E.g. in serde you _cannot_ write `default="42"`, instead you have to wrap const-values in a static function. - at least the last time I checked the documentation.

**Comment by TedDriggs** [comment]
> I still believe that 100% serde-behaviour is not a good fit for derive_builder. E.g. in serde you cannot write default="42", instead you have to wrap const-values in a static function. - at least the last time I checked the documentation.

This is accurate. Is there maybe a way to check at compile time that the user has either passed:

1. A value literal that implements `Copy` or
1. A path to a function?

That could disallow the exotic misuses while still allowing the desired simple case.

**Comment by colin-kiegel** [comment]
A custom derive can only inspect the source code of the item it is applied to. Nothing more - so we don't know what's in scope and what implements what. We're completely blind to the world. :-)

**Comment by TedDriggs** [comment]
:( bummer. Okay, in that case I'm out of ideas on this one.

**Comment by colin-kiegel** [comment]
I thinks it's the best we can do right now. I'll close in the meantime.
