### ISSUE TITLE
skip/rename/private build method

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#70]
Right now we always generate the build method with a fixed name, and we give it the same privacy as the builder struct.

It would be nice to customize all of that, such that users can wrap a private build method, or just skip it entirely and do their own thing.

This should be rather straightforward to implement. If anyone is interested to start contributing to this crate, this would be a good entry point. :-)

The major question is, how to namespace these options
- `#[builder(build_fn(skip, private, name="finalize"))]`
- `#[builder(buildfn(...))]`
- `#[builder(build(...))]`
- `#[builder(fn(...))]`

All of the possible names I can currently think of look a bit weird.

**Comment by TedDriggs** [comment]
How about `build_fn`?

**Comment by colin-kiegel** [comment]
added that to the list as primary candidate

**Comment by TedDriggs** [comment]
I'm working on this now, if you want to assign the issue to me.

**Comment by colin-kiegel** [comment]
Ok, in the master branch we have now all of the above, except setting the build fn visibility. With the next release I'll probably open another ticket for that, so we can discuss/track it there. :-)

@TedDriggs thank you very much.

**Comment by colin-kiegel** [comment]
released with v0.4.5 - thanks @TedDriggs :-)
