### ISSUE TITLE
failing doc test

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#75]
I un-ignored this doc-test and somehow `dev/githook.sh` didn't catch this.
* we don't have `setter(name = "...")` yet - my bad.
* need to take a closer look at why `dev/githook.sh` didn't work

I'll fix this later https://travis-ci.org/colin-kiegel/rust-derive-builder/jobs/221262990#L2912. Have to go now. :-)

```rust
//! # #[cfg(feature = "nightlytests")]
//! #[derive(Builder, Debug, PartialEq)]
//! struct Ipsum {
//!     #[builder(try_setter, setter(into, name = "foo"))]
//!     pub dolor: u8,
//! }
```
```
error: proc-macro derive panicked
  --> <anon>:16:10
   |
16 | #[derive(Builder, Debug, PartialEq)]
   |          ^^^^^^^
   |
   = help: message: Unknown setter option `name` on field `dolor`.
```

PS: one way of fixing would be to implement `name = "..."` ^^

**Comment by TedDriggs** [comment]
`name = "..."` should also change the emitted field name? I'm pretty busy today, but will happily take a look later this week.

**Comment by colin-kiegel** [comment]
@TedDriggs Thx - I'll take this one (I'm already on it). Actually 90% of this feature was already in the codebase, but then I just forgot to finish it. ^^
