### ISSUE TITLE
coveralls and doc-upload don't work

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#8]
I'll look into it later.

**Comment by colin-kiegel** [comment]
We have docs now: https://colin-kiegel.github.io/rust-derive-builder/ - but it's not much right now.

But I have no idea, why coveralls still doesn't work. Well enough for today.

**Comment by killercup** [comment]
Hm, the macro docs get kinda lost after that huge listing of macro code. Should we move them into the main crate docs?

**Comment by colin-kiegel** [comment]
yes, we should - I'll look into it now. :-)

**Comment by killercup** [comment]
Oh, see my PR!


Colin Kiegel <notifications@github.com> schrieb am So. 7. Aug. 2016 um
11:26:

**Comment by colin-kiegel** [comment]
right, thx - I will merge it manually, due to merge conflict.

**Comment by killercup** [comment]
👍


Colin Kiegel <notifications@github.com> schrieb am So. 7. Aug. 2016 um
11:30:

**Comment by colin-kiegel** [comment]
ok, done - docs look good now. :-)
