### ISSUE TITLE
once-only setter: prevent overriding existing value

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#81]
Current setters always override the previous value. But sometimes you want to emit a warning that the value was already set. E.g. derive_builder itself has the use case where it wants to warn you about something like `#[builder(name="Foo", name="Bar")]`.

In such a case I could imagine a setting `#[builder(setter(once))]`, which would error if the setter was called multiple times. The setter would need to change signature and the previous value could be contained in the error. 

# Atlernatives

- let the user handle this situation _manually_ via public builder fields or getters #7 

# Drawbacks

- We already have fallible setters which are generic over `TryFrom` #72. These are  activated via `#[builder(try_setter)]` and have a `try_` prefix by default. It might be a bit weird to have to sets of fallible setters `#[builder(try_setter)]` and `#[builder(setter(once))]` which do _different_ things. What if someone wants to have `#[builder(try_setter(once))]`? Would we even allow that? (We would need to wrap to different error types).
- Again we face the problem that proc macro crates can't export items (*sigh*). But we would need to bring an error type into scope. Deriving unique (but otherwise identical) error types per builder seems to be an ugly hack.

**Comment by TedDriggs** [comment]
Due to the lack of reported need for these, I'm closing this issue. The idea is interesting, but it doesn't seem to be a priority for the crate's users.
