### ISSUE TITLE
default builder pattern

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#88]
A while ago, we [had a discussion](https://github.com/colin-kiegel/rust-derive-builder/issues/2) whether the default builder pattern should be consuming or not (`self` vs. `&mut self`). We arrived at `&mut self`.

I would like to revive that discussion. There is no rush - let's just collect arguments for both sides.

Pro `self`
- the whole approach of our builder is un-wraping `Option`s and copying/moving their data. A consuming API expresses this fact best.
- no clones guaranteed (we don't have to rely on the compiler being smart enough to _always_ compile them away)
- [nested builders inside try-setters](https://github.com/colin-kiegel/rust-derive-builder/pull/77#issuecomment-296314882)
- ...

Pro `&mut self`
- complex/conditional configuration is more convenient
- [inofficial Rust design patterns suggest this as preferred default](https://aturon.github.io/ownership/builders.html)
- no (breaking) change required
- ...

**Comment by TedDriggs** [comment]
> the whole approach of our builder is un-wrapping Options and copying/moving their data. A consuming API expresses this fact best.

The API already consumes the values passed to the setters, so we're idiomatic in that regard.

> [nested builders inside try-setters](https://github.com/colin-kiegel/rust-derive-builder/pull/77#issuecomment-296314882)

This works with the `&mut self` pattern too; it just requires there be an extra trait impl for the `&mut FooBuilder` case.

One argument in favor of `&mut self` is this code:

```rust
fn build_opts(cli: CliArgs, env: EnvArgs) -> Result<Foo, String> {
    let mut foo = FooBuilder::default();
    
    if let Err(_) = foo.try_mode(cli.mode()) {
        foo.try_mode(env.mode())?;
    }
    
    foo.host(cli.host()).build()
}
```

In this code, a consuming builder wouldn't work unless the user cloned the builder before the attempt was made. That seems much less efficient. Also, a consuming pattern requires chaining or assignment any time a field is set, which complicates the data flows considerably.
