### ISSUE TITLE
build function visibility

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-derive-builder#89]
Since PR #70 added skipping and renaming of the build function. But we can't set the visibility. It might be useful to implement hidden build functions to be able to wrap them in a custom public build function.

This should be rather straightforward to implement. If anyone is interested to start contributing to this crate, this would be a good entry point. :-)

- `#[builder(build_fn(private))]` (cmp with `#[builder(setter(private))]`)

**Comment by TedDriggs** [comment]
This becomes trivial once #120 is merged.
