### ISSUE TITLE
Consider new public/private declaration format to account for restricted visibility

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#96]
With restricted visibility stabilizing in 1.18 (see rust-lang/rust#32409), it would be good for `derive_builder` to support declaring restricted visibility for the generated structs, setters, and fields.

# Proposal
```rust
#[derive(Builder)]
#[builder(vis = "pub(crate)")]
pub(crate) struct Foo {
    bar: u8
}
```

This would also be available in the `setter`, `field`, and `build_fn` sub-options. We could keep the current `#[builder(public)]` option for compatibility, but I think it probably makes sense to deprecate it since the method above is more future-proof (and easier to validate that it only appears once).

**Comment by colin-kiegel** [comment]
Sounds  reasonable

* What would be the new expression for `#[builder(setter(private))]`? This is needed for overrides. Would it be `vis=""` or `vis="priv"`? Both don't look particularly good IMO.

**Comment by colin-kiegel** [comment]
Alternatively we could introduce `#[builder(pub(crate)]` or `#[builder(public(crate)]`...

**Comment by TedDriggs** [comment]
I tried `#[builder(pub(crate))]`, but that doesn't seem to work because the format uses `pub(in mod)`, which won't get passed by `syn` as a valid meta-item. The private thing is interesting; don't have a good answer there.

**Comment by TedDriggs** [comment]
We haven't heard any requests for this; closing it.
