### ISSUE TITLE
Owned builders should not #[derive(Clone)]

### ISSUE THREAD

**Issue by chpio** [colin-kiegel/rust-derive-builder#97]
Hi,

my struct has a non-clonable field, thus i want to disable the derived impl of *Clone* trait for the generated builder.

**Comment by colin-kiegel** [comment]
We need `Clone` only for the mutable and immutable pattern. Would the owned pattern work for you? We could disable `#[derive(Clone)]` there.

**Comment by fluffysquirrels** [comment]
I have the same constraint, and the owned pattern would work fine for me.

**Comment by spearman** [comment]
This would be nice to have in the "owned" variant. I think you could get around it by wrapping the offending field in an reference counted pointer, but usually I would prefer to avoid the extra level of indirection.

**Comment by ruabmbua** [comment]
Me too.

**Comment by azriel91** [comment]
Me too. I had a go at this in #111, but code placement is debatable :slightly_smiling_face:
