### ISSUE TITLE
#[builder(private)] should actually set struct visibility

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#99]
In the course of refactoring, I came across the test `setter_visibility::public_setters_override_foreign_module`

```rust
pub mod foo {
    #[derive(Debug, PartialEq, Default, Builder, Clone)]
    #[builder(private, setter(into))]
    pub struct Lorem {
        pub private: String,
        #[builder(public)]
        pub public: String,
    }

    #[derive(Debug, PartialEq, Default, Builder, Clone)]
    #[builder(public, setter(into))]
    pub struct Ipsum {
        #[builder(private)]
        pub private: String,
        pub public: String,
    }
}

#[test]
#[should_panic(expected="`private` must be initialized")]
fn public_setters_override_foreign_module() {
    This test seems very odd; public setters force the struct to be public?
    let x = foo::LoremBuilder::default()
        .public("Hello")
        .build()
        .unwrap();

    assert_eq!(x.public, "Hello".to_string());
}
```

As written, this test seems very odd to me. If the builder struct itself was declared private, why should any public setter override that? It's idiomatic to have a private struct with public methods, especially with restricted visibility landing in stable in 1.18.

# Proposal
I'd vote we change this behavior in v0.5.0; field-level visibility settings shouldn't be able to change struct visibility. We could add a warning for this temporarily, but I don't think it makes sense to preserve the old behavior behind a flag.

**Comment by colin-kiegel** [comment]
@TedDriggs did we forget to do this?
